/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 03 04:31:00 GMT 2026
 */

package comp5111.assignment.cut;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import comp5111.assignment.cut.Subject;
import java.nio.ByteBuffer;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class Subject_evosuite66_ESTest  {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("0007-07-31", "0007-07-31");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      subject_GameConfiguration0.clearInitialBoard();
      assertEquals(25, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(11);
      boolean boolean0 = subject_GameConfiguration0.isBoardFull();
      assertEquals(11, subject_GameConfiguration0.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("");
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(11);
      subject_GameConfiguration0.getPlacesOfPlayer(subject_GamePlayer0);
      assertEquals(11, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      boolean boolean0 = subject_GameConfiguration0.isBoardSymmetric();
      assertEquals(7, subject_GameConfiguration0.getSize());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      int[] intArray0 = subject_GameConfiguration0.countPiecesPerPlayer();
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertEquals(2, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(11);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(3, 2175);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertEquals(11, subject_GameConfiguration0.getSize());
      assertEquals(2175, subject_GamePlace0.y());
      assertEquals(3, subject_GamePlace0.x());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, '\u0000');
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertEquals(7, subject_GameConfiguration0.getSize());
      assertEquals(0, subject_GamePlace0.y());
      assertEquals(0, subject_GamePlace0.x());
      assertEquals("(0, 0)", subject_GamePlace0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(11);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1047, 2175);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertEquals(11, subject_GameConfiguration0.getSize());
      assertEquals(2175, subject_GamePlace0.y());
      assertTrue(boolean0);
      assertEquals(1047, subject_GamePlace0.x());
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, (-367));
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertEquals(0, subject_GamePlace0.x());
      assertEquals((-367), subject_GamePlace0.y());
      assertTrue(boolean0);
      assertEquals(3, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-47), (-1660));
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertEquals("(-47, -1660)", subject_GamePlace0.toString());
      assertTrue(boolean0);
      assertEquals((-47), subject_GamePlace0.x());
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      String string0 = subject_GameConfiguration0.toString();
      assertEquals("GameConfiguration (size=7)\n. . . . . . .\n. . . . . . .\n. . . . . . .\n. . . . . . .\n. . . . . . .\n. . . . . . .\n. . . . . . .\n", string0);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, '\u0000');
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
      assertEquals(7, subject_GameConfiguration0.getSize());
      assertEquals(0, subject_GamePlace0.x());
      assertEquals(0, subject_GamePlace0.y());
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-343), 138);
      subject_GamePlace0.x(1);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(366, 11);
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(11);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, (-3141));
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-375), (-224));
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(11);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      Subject.GamePlayer[][] subject_GamePlayerArray0 = subject_GameConfiguration0.getInitialBoard();
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertEquals(25, subject_GamePlayerArray0.length);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[1];
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(7, subject_GamePlayerArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // there must be exactly two players
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(79);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard is at most 25
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(562);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be an odd number
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be at least 3
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-343), 138);
      int int0 = subject_GamePlace0.manhattanDistance((Subject.GamePlace) null);
      assertEquals("(-343, 138)", subject_GamePlace0.toString());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(13, (-2163));
      int int0 = subject_GamePlace0.manhattanDistance(subject_GamePlace0);
      assertEquals("(13, -2163)", subject_GamePlace0.toString());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, (-1));
      Subject.GamePlace subject_GamePlace1 = subject0.new GamePlace(0, 0);
      boolean boolean0 = subject_GamePlace0.isAdjacent(subject_GamePlace1);
      assertEquals("(0, -1)", subject_GamePlace0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-1601), (-1601));
      boolean boolean0 = subject_GamePlace0.isAdjacent((Subject.GamePlace) null);
      assertEquals("(-1601, -1601)", subject_GamePlace0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(13, (-2163));
      boolean boolean0 = subject_GamePlace0.isAdjacent(subject_GamePlace0);
      assertFalse(boolean0);
      assertEquals("(13, -2163)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(840, 840);
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      subject_GamePlace1.y(918);
      boolean boolean0 = subject_GamePlace1.equals(subject_GamePlace0);
      assertEquals(918, subject_GamePlace1.y());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 0);
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      subject_GamePlace1.x(4);
      boolean boolean0 = subject_GamePlace1.equals(subject_GamePlace0);
      assertEquals("(4, 0)", subject_GamePlace1.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(110, (-614));
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      boolean boolean0 = subject_GamePlace1.equals(subject_GamePlace0);
      assertEquals("(110, -614)", subject_GamePlace1.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(97, 2795);
      boolean boolean0 = subject_GamePlace0.equals((Object) null);
      assertEquals("(97, 2795)", subject_GamePlace0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(Integer.MIN_VALUE, Integer.MIN_VALUE);
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace0);
      assertEquals("(-2147483648, -2147483648)", subject_GamePlace0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-375), (-224));
      Object object0 = new Object();
      boolean boolean0 = subject_GamePlace0.equals(object0);
      assertEquals("(-375, -224)", subject_GamePlace0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("--65Iy");
      Object object0 = new Object();
      boolean boolean0 = subject_GamePlayer0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      boolean boolean0 = subject_GamePlayer0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("-826 S");
      boolean boolean0 = subject_GamePlayer0.equals(subject_GamePlayer0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, (-367));
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // the player of the piece is unknown
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(115, 1, (-1), 115);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween((-1), 7, 138, 7);
      assertEquals(1668, int0);
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween((byte) (-24), (byte)2, (byte)70, (byte) (-24));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(88, 130, (-1487), 6);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(1165, (-1131), 25, 1165);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth(6, 0);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth(6, 6);
      assertEquals("0006-06-30", string0);
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth((-2614), 6);
      assertEquals("-2614-06-01", string0);
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth((-1), 2765);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth(225, (-15));
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      // Undeclared exception!
      Subject.DateTimeAlgorithms.listDatesBetween(8, 3, 8, 3, 3, 8);
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(27, 1, 1, 1, 1, (-1));
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(2765, 24, 3541);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("%04d-%02d-%02d", "%04d-%02d-%02d");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("--6'Q}*+8y=Cl", "8P");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("", "94w??'Ya,^_v,_(");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysInYear((-2872));
      assertEquals(366, int0);
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysInYear((-343));
      assertEquals(365, int0);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(870);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(12);
      assertEquals("Dec", string0);
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(10);
      assertEquals("Oct", string0);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(9);
      assertEquals("Sep", string0);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(1047, 8, 8);
      assertEquals("8th Aug 1047", string0);
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(7, 7, 7);
      assertEquals("7th Jul 7", string0);
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(5);
      assertEquals("May", string0);
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(4);
      assertEquals("Apr", string0);
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(3);
      assertEquals("Mar", string0);
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(2);
      assertEquals("Feb", string0);
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(1);
      assertEquals("Jan", string0);
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("siz");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Oct");
      assertEquals(10, int0);
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Nov");
      assertEquals(11, int0);
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("May");
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Mar");
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jun");
      assertEquals(6, int0);
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jul");
      assertEquals(7, int0);
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jan");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Feb");
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Dec");
      assertEquals(12, int0);
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Aug");
      assertEquals(8, int0);
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Sep");
      assertEquals(9, int0);
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("[UKk");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month((String) null);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(11);
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(4);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(3);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(7);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(29);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter((-3185));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr((-30));
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(1103);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(1);
      assertEquals("1st", string0);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(1047, 11, 11);
      assertEquals("11th Nov 1047", string0);
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(102);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(1259);
      assertEquals("21 M", string0);
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(6020L);
      assertEquals("2 H", string0);
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(24);
      assertEquals("24 S", string0);
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(604800L);
      assertEquals("1 W", string0);
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(86400000L);
      assertEquals("3 Y", string0);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(86400L);
      assertEquals("1 D", string0);
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      boolean boolean0 = Subject.DateTimeAlgorithms.judgeLeapYear(100);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(0, 2, (-200), (-2153), 2, 3);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween((-1624), 9, (-1624), (-3562), (-3562), 9);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(6, 6, 6);
      assertEquals("6th Jun 6", string0);
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.calcDaysInMonth(14, 4);
      assertEquals(30, int0);
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.DateTimeAlgorithms.daysBetweenDates((-1662), 2, 2341, 0, 2061, (-1713));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid date
         //
         verifyException("comp5111.assignment.cut.Subject$DateTimeAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.calcDaysInMonth(6142, 67);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.DateTimeAlgorithms.daysBetweenDates((byte) (-3), (byte)1, 16, (byte)1, (byte)11, (-212851967));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid date
         //
         verifyException("comp5111.assignment.cut.Subject$DateTimeAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.DateTimeAlgorithms.daysBetweenDates(0, 0, 632, (-73), 342, (-800));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid date
         //
         verifyException("comp5111.assignment.cut.Subject$DateTimeAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padRight((String) null, (short) (-2219), 'Q');
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padRight("comp5111.assignment.cut.Subject$GameConfiguration", (short)1955, ')');
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padLeft("g", (short) (-1402), 'x');
      assertEquals("g", string0);
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padLeft((String) null, (short)108, 'W');
      assertEquals("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", string0);
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo(".");
      assertNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("GameConfiguration (size=7)\n. . . . . . .\n. . . . . . .\n. . . . . . .\n. . . . . . .\n. . . . . . .\n. . . . . . .\n. . . . . . .\n");
      assertNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("");
      assertNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo((String) null);
      assertNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("1 D");
      assertNotNull(intArray0);
      assertArrayEquals(new int[] {0, 0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      int int0 = Subject.StringAlgorithms.extractIntInStr("");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      int int0 = Subject.StringAlgorithms.extractIntInStr((String) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("Y ppnZViEqSn}Yr6");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // Character Y is neither a decimal digit number, decimal point, nor \"e\" notation exponential mark.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("1 D");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // Character   is neither a decimal digit number, decimal point, nor \"e\" notation exponential mark.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test119()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("%04d-%02d-%02d");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // Character % is neither a decimal digit number, decimal point, nor \"e\" notation exponential mark.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test120()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("JF08yqmvF");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test121()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber(">Cf");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test122()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("-exd'`}*+hy=l");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // -exd'`}*+hy=l
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test123()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber(")Tvc.SGg=@ {cQzsjl");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // )Tvc.SGg=@ {cQzsjl
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test124()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("-0>9'`*+d8y=Cl");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // -0>9'`*+d8y=Cl
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test125()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("Invalid date");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // Invalid date
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test126()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("s.ze of gaieboard must bepat least 3");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // Character array is missing \"e\" notation exponential mark.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test127()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("$qe.t?V]bH");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // $qe.t?V]bH
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test128()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber(".2");
      assertEquals((short)0, number0.shortValue());
  }

  @Test(timeout = 4000)
  public void test129()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("-0x9'`}*+8y=Cl");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"-9'`}*+8y=Cl\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test130()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("0x.nVN0O9");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \".nVN0O9\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test131()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("--comp5111.assignment.cut.Subject$GamePlayer");
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test132()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("n");
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test133()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("9");
      assertEquals((short)9, number0.shortValue());
  }

  @Test(timeout = 4000)
  public void test134()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("");
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test135()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber((String) null);
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test136()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("2L");
      assertEquals((byte)2, number0.byteValue());
  }

  @Test(timeout = 4000)
  public void test137()  throws Throwable  {
      char[] charArray0 = new char[16];
      charArray0[4] = 'Q';
      String string0 = Subject.StringAlgorithms.parseToken("=U[dDkbutQZ<K", charArray0);
      assertEquals("=U[dDkbut", string0);
  }

  @Test(timeout = 4000)
  public void test138()  throws Throwable  {
      char[] charArray0 = new char[1];
      String string0 = Subject.StringAlgorithms.parseToken("(invalid)", charArray0);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test139()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("(invalid)", "|x_^c", "|x_^c", "(invalid)");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test140()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("", (String) null, "", "");
      assertFalse(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test141()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.strToBoolean("", "the player of the piece is unknow|", "Y", "1!(W\"k");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test142()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.strToBoolean((String) null, "^]pV!Uo>PaEnBXx&o", "-0x", "0x:,-\"");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test143()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null, (String) null, (String) null, "(i");
      assertNotNull(boolean0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test144()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null, (String) null, (String) null, (String) null);
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test145()  throws Throwable  {
      String[] stringArray0 = new String[5];
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean(stringArray0[3], "--", stringArray0[0], "\"szdbe(M?>^_axM");
      assertFalse(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test146()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("(invalid)", "(invalid)", "(invalid)", "(invalid)");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test147()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("<jwdL");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test148()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("bo3X");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test149()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("T6IU");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test150()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Yvm");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test151()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("x~m");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test152()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("o3w");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test153()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("O3X");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test154()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("ON");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test155()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("O3");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test156()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("oh");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test157()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("nh");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test158()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("f");
      assertNotNull(boolean0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test159()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("N");
      assertNotNull(boolean0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test160()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("n");
      assertNotNull(boolean0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test161()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("S");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test162()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Y");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test163()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("y");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test164()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("t");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test165()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null);
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test166()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("--#y:5&SMR\"lQLE");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test167()  throws Throwable  {
      byte[] byteArray0 = new byte[3];
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.enlarge((-1195), byteArray0, (byte)70);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test168()  throws Throwable  {
      byte[] byteArray0 = new byte[5];
      Subject.StringAlgorithms.enlarge(840, byteArray0, 1);
      assertEquals(5, byteArray0.length);
  }

  @Test(timeout = 4000)
  public void test169()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      byteArray0[0] = (byte) (-1);
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.decodeOctets(14, byteBuffer0, (StringBuilder) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test170()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      StringBuilder stringBuilder0 = new StringBuilder((byte)84);
      int int0 = Subject.StringAlgorithms.decodeOctets(0, byteBuffer0, stringBuilder0);
      assertEquals(2, int0);
      assertEquals(1, byteBuffer0.remaining());
  }

  @Test(timeout = 4000)
  public void test171()  throws Throwable  {
      ByteBuffer byteBuffer0 = ByteBuffer.allocate(255);
      StringBuilder stringBuilder0 = new StringBuilder("|x_^c");
      int int0 = Subject.StringAlgorithms.decodeOctets((-1), byteBuffer0, stringBuilder0);
      assertEquals("|x_^c\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000", stringBuilder0.toString());
      assertEquals(763, int0);
  }

  @Test(timeout = 4000)
  public void test172()  throws Throwable  {
      String[] stringArray0 = new String[3];
      stringArray0[0] = ">otL;\"Obp$=}0'4";
      String[] stringArray1 = Subject.StringAlgorithms.trimArrayElements(stringArray0);
      assertEquals(3, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test173()  throws Throwable  {
      String[] stringArray0 = new String[0];
      String[] stringArray1 = Subject.StringAlgorithms.trimArrayElements(stringArray0);
      assertEquals(0, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test174()  throws Throwable  {
      String[] stringArray0 = Subject.StringAlgorithms.trimArrayElements((String[]) null);
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test175()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("--6'Q}*+8y=Cl", "8P");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test176()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("Mar", "Mar");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test177()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("(invalid)", (String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test178()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("", "ftEgMxE{az-kMd8i ");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test179()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase((String) null, (String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test180()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("--65Iy");
      subject_GamePlayer0.addScore(0);
      assertEquals(0, subject_GamePlayer0.getScore());
  }

  @Test(timeout = 4000)
  public void test181()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayer0.resetScore();
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
  }

  @Test(timeout = 4000)
  public void test182()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("(invalid)");
      String string0 = subject_GamePlayer0.getName();
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test183()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      Subject.GameConfiguration subject_GameConfiguration1 = subject_GameConfiguration0.clone();
      assertEquals(7, subject_GameConfiguration1.getSize());
  }

  @Test(timeout = 4000)
  public void test184()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayer0.setScore((-1968));
      assertEquals("GamePlayer{name='Anonymous Player', score=-1968}", subject_GamePlayer0.toString());
  }

  @Test(timeout = 4000)
  public void test185()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("3N");
      int int0 = subject_GamePlayer0.getScore();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test186()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      String string0 = subject_GamePlayer0.toString();
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", string0);
  }

  @Test(timeout = 4000)
  public void test187()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      int int0 = subject_GameConfiguration0.getSize();
      assertEquals(7, int0);
  }

  @Test(timeout = 4000)
  public void test188()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      subject_GameConfiguration0.getPlayers();
      assertEquals(3, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test189()  throws Throwable  {
      Subject.StringAlgorithms subject_StringAlgorithms0 = new Subject.StringAlgorithms();
  }

  @Test(timeout = 4000)
  public void test190()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getEmptyPlaces();
      assertEquals(48, list0.size());
  }

  @Test(timeout = 4000)
  public void test191()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 0);
      String string0 = subject_GamePlace0.toString();
      assertEquals("(0, 0)", string0);
  }

  @Test(timeout = 4000)
  public void test192()  throws Throwable  {
      Subject.DateTimeAlgorithms subject_DateTimeAlgorithms0 = new Subject.DateTimeAlgorithms();
  }
}
