/*
 * This file was automatically generated by EvoSuite
 * Thu May 07 10:59:40 GMT 2026
 */

package comp5111.assignment.cut;

import org.junit.Test;
import static org.junit.Assert.*;
import comp5111.assignment.cut.Subject;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Subject$GamePlace_ESTest extends Subject$GamePlace_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1416, (-4135));
      assertEquals("(1416, -4135)", subject_GamePlace0.toString());
      assertEquals((-4135), subject_GamePlace0.y());
      assertEquals(1416, subject_GamePlace0.x());
      assertNotNull(subject_GamePlace0);
      
      int int0 = subject_GamePlace0.manhattanDistance((Subject.GamePlace) null);
      assertEquals("(1416, -4135)", subject_GamePlace0.toString());
      assertEquals((-4135), subject_GamePlace0.y());
      assertEquals(1416, subject_GamePlace0.x());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(921, 921);
      assertEquals("(921, 921)", subject_GamePlace0.toString());
      assertEquals(921, subject_GamePlace0.x());
      assertEquals(921, subject_GamePlace0.y());
      assertNotNull(subject_GamePlace0);
      
      int int0 = subject_GamePlace0.manhattanDistance(subject_GamePlace0);
      assertEquals("(921, 921)", subject_GamePlace0.toString());
      assertEquals(921, subject_GamePlace0.x());
      assertEquals(921, subject_GamePlace0.y());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(921, 921);
      assertEquals("(921, 921)", subject_GamePlace0.toString());
      assertEquals(921, subject_GamePlace0.y());
      assertEquals(921, subject_GamePlace0.x());
      assertNotNull(subject_GamePlace0);
      
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals("(921, 921)", subject_GamePlace0.toString());
      assertEquals(921, subject_GamePlace0.y());
      assertEquals(921, subject_GamePlace0.x());
      assertEquals(921, subject_GamePlace1.y());
      assertEquals(921, subject_GamePlace1.x());
      assertEquals("(921, 921)", subject_GamePlace1.toString());
      assertTrue(subject_GamePlace1.equals((Object)subject_GamePlace0));
      assertNotNull(subject_GamePlace1);
      
      subject_GamePlace1.x(0);
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals("(921, 921)", subject_GamePlace0.toString());
      assertEquals(921, subject_GamePlace0.y());
      assertEquals(921, subject_GamePlace0.x());
      assertEquals("(0, 921)", subject_GamePlace1.toString());
      assertEquals(921, subject_GamePlace1.y());
      assertEquals(0, subject_GamePlace1.x());
      assertFalse(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertFalse(subject_GamePlace1.equals((Object)subject_GamePlace0));
      
      subject_GamePlace0.x((-1));
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertEquals(921, subject_GamePlace0.y());
      assertEquals((-1), subject_GamePlace0.x());
      assertEquals("(-1, 921)", subject_GamePlace0.toString());
      assertFalse(subject_GamePlace0.equals((Object)subject_GamePlace1));
      
      boolean boolean0 = subject_GamePlace1.isAdjacent(subject_GamePlace0);
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals(921, subject_GamePlace0.y());
      assertEquals((-1), subject_GamePlace0.x());
      assertEquals("(-1, 921)", subject_GamePlace0.toString());
      assertEquals("(0, 921)", subject_GamePlace1.toString());
      assertEquals(921, subject_GamePlace1.y());
      assertEquals(0, subject_GamePlace1.x());
      assertTrue(boolean0);
      assertFalse(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertFalse(subject_GamePlace1.equals((Object)subject_GamePlace0));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1416, (-4135));
      assertEquals(1416, subject_GamePlace0.x());
      assertEquals("(1416, -4135)", subject_GamePlace0.toString());
      assertEquals((-4135), subject_GamePlace0.y());
      assertNotNull(subject_GamePlace0);
      
      boolean boolean0 = subject_GamePlace0.isAdjacent((Subject.GamePlace) null);
      assertEquals(1416, subject_GamePlace0.x());
      assertEquals("(1416, -4135)", subject_GamePlace0.toString());
      assertEquals((-4135), subject_GamePlace0.y());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(921, 921);
      assertEquals("(921, 921)", subject_GamePlace0.toString());
      assertEquals(921, subject_GamePlace0.x());
      assertEquals(921, subject_GamePlace0.y());
      assertNotNull(subject_GamePlace0);
      
      boolean boolean0 = subject_GamePlace0.isAdjacent(subject_GamePlace0);
      assertEquals("(921, 921)", subject_GamePlace0.toString());
      assertEquals(921, subject_GamePlace0.x());
      assertEquals(921, subject_GamePlace0.y());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(359, 359);
      assertEquals("(359, 359)", subject_GamePlace0.toString());
      assertEquals(359, subject_GamePlace0.x());
      assertEquals(359, subject_GamePlace0.y());
      assertNotNull(subject_GamePlace0);
      
      Subject.GamePlace subject_GamePlace1 = subject0.new GamePlace(359, 2813);
      assertEquals(2813, subject_GamePlace1.y());
      assertEquals(359, subject_GamePlace1.x());
      assertEquals("(359, 2813)", subject_GamePlace1.toString());
      assertFalse(subject_GamePlace1.equals((Object)subject_GamePlace0));
      assertNotNull(subject_GamePlace1);
      
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace1);
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals("(359, 359)", subject_GamePlace0.toString());
      assertEquals(359, subject_GamePlace0.x());
      assertEquals(359, subject_GamePlace0.y());
      assertEquals(2813, subject_GamePlace1.y());
      assertEquals(359, subject_GamePlace1.x());
      assertEquals("(359, 2813)", subject_GamePlace1.toString());
      assertFalse(boolean0);
      assertFalse(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertFalse(subject_GamePlace1.equals((Object)subject_GamePlace0));
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(359, 359);
      assertEquals("(359, 359)", subject_GamePlace0.toString());
      assertEquals(359, subject_GamePlace0.x());
      assertEquals(359, subject_GamePlace0.y());
      assertNotNull(subject_GamePlace0);
      
      Subject.GamePlace subject_GamePlace1 = subject0.new GamePlace(0, 359);
      assertEquals(0, subject_GamePlace1.x());
      assertEquals("(0, 359)", subject_GamePlace1.toString());
      assertEquals(359, subject_GamePlace1.y());
      assertFalse(subject_GamePlace1.equals((Object)subject_GamePlace0));
      assertNotNull(subject_GamePlace1);
      
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace1);
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals("(359, 359)", subject_GamePlace0.toString());
      assertEquals(359, subject_GamePlace0.x());
      assertEquals(359, subject_GamePlace0.y());
      assertEquals(0, subject_GamePlace1.x());
      assertEquals("(0, 359)", subject_GamePlace1.toString());
      assertEquals(359, subject_GamePlace1.y());
      assertFalse(boolean0);
      assertFalse(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertFalse(subject_GamePlace1.equals((Object)subject_GamePlace0));
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(359, 359);
      assertEquals(359, subject_GamePlace0.y());
      assertEquals(359, subject_GamePlace0.x());
      assertEquals("(359, 359)", subject_GamePlace0.toString());
      assertNotNull(subject_GamePlace0);
      
      boolean boolean0 = subject_GamePlace0.equals((Object) null);
      assertEquals(359, subject_GamePlace0.y());
      assertEquals(359, subject_GamePlace0.x());
      assertEquals("(359, 359)", subject_GamePlace0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(359, 359);
      assertEquals("(359, 359)", subject_GamePlace0.toString());
      assertEquals(359, subject_GamePlace0.x());
      assertEquals(359, subject_GamePlace0.y());
      assertNotNull(subject_GamePlace0);
      
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace0);
      assertEquals("(359, 359)", subject_GamePlace0.toString());
      assertEquals(359, subject_GamePlace0.x());
      assertEquals(359, subject_GamePlace0.y());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(921, 921);
      assertEquals(921, subject_GamePlace0.y());
      assertEquals(921, subject_GamePlace0.x());
      assertEquals("(921, 921)", subject_GamePlace0.toString());
      assertNotNull(subject_GamePlace0);
      
      boolean boolean0 = subject_GamePlace0.equals(subject0);
      assertEquals(921, subject_GamePlace0.y());
      assertEquals(921, subject_GamePlace0.x());
      assertEquals("(921, 921)", subject_GamePlace0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1416, (-4135));
      assertEquals("(1416, -4135)", subject_GamePlace0.toString());
      assertEquals((-4135), subject_GamePlace0.y());
      assertEquals(1416, subject_GamePlace0.x());
      assertNotNull(subject_GamePlace0);
      
      subject_GamePlace0.hashCode();
      assertEquals("(1416, -4135)", subject_GamePlace0.toString());
      assertEquals((-4135), subject_GamePlace0.y());
      assertEquals(1416, subject_GamePlace0.x());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(921, 921);
      assertEquals(921, subject_GamePlace0.x());
      assertEquals(921, subject_GamePlace0.y());
      assertEquals("(921, 921)", subject_GamePlace0.toString());
      assertNotNull(subject_GamePlace0);
      
      subject_GamePlace0.y(921);
      assertEquals(921, subject_GamePlace0.x());
      assertEquals(921, subject_GamePlace0.y());
      assertEquals("(921, 921)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(359, 359);
      assertEquals(359, subject_GamePlace0.y());
      assertEquals(359, subject_GamePlace0.x());
      assertEquals("(359, 359)", subject_GamePlace0.toString());
      assertNotNull(subject_GamePlace0);
      
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals(359, subject_GamePlace0.y());
      assertEquals(359, subject_GamePlace0.x());
      assertEquals("(359, 359)", subject_GamePlace0.toString());
      assertEquals(359, subject_GamePlace1.x());
      assertEquals("(359, 359)", subject_GamePlace1.toString());
      assertEquals(359, subject_GamePlace1.y());
      assertTrue(subject_GamePlace1.equals((Object)subject_GamePlace0));
      assertNotNull(subject_GamePlace1);
      
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace1);
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals(359, subject_GamePlace0.y());
      assertEquals(359, subject_GamePlace0.x());
      assertEquals("(359, 359)", subject_GamePlace0.toString());
      assertEquals(359, subject_GamePlace1.x());
      assertEquals("(359, 359)", subject_GamePlace1.toString());
      assertEquals(359, subject_GamePlace1.y());
      assertTrue(boolean0);
      assertTrue(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertTrue(subject_GamePlace1.equals((Object)subject_GamePlace0));
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-1819), 0);
      assertEquals("(-1819, 0)", subject_GamePlace0.toString());
      assertEquals((-1819), subject_GamePlace0.x());
      assertEquals(0, subject_GamePlace0.y());
      assertNotNull(subject_GamePlace0);
      
      int int0 = subject_GamePlace0.x();
      assertEquals("(-1819, 0)", subject_GamePlace0.toString());
      assertEquals((-1819), subject_GamePlace0.x());
      assertEquals(0, subject_GamePlace0.y());
      assertEquals((-1819), int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1416, (-4135));
      assertEquals((-4135), subject_GamePlace0.y());
      assertEquals("(1416, -4135)", subject_GamePlace0.toString());
      assertEquals(1416, subject_GamePlace0.x());
      assertNotNull(subject_GamePlace0);
      
      int int0 = subject_GamePlace0.y();
      assertEquals((-4135), subject_GamePlace0.y());
      assertEquals("(1416, -4135)", subject_GamePlace0.toString());
      assertEquals(1416, subject_GamePlace0.x());
      assertEquals((-4135), int0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 0);
      assertEquals(1, subject_GamePlace0.x());
      assertEquals(0, subject_GamePlace0.y());
      assertEquals("(1, 0)", subject_GamePlace0.toString());
      assertNotNull(subject_GamePlace0);
      
      String string0 = subject_GamePlace0.toString();
      assertEquals(1, subject_GamePlace0.x());
      assertEquals(0, subject_GamePlace0.y());
      assertEquals("(1, 0)", subject_GamePlace0.toString());
      assertEquals("(1, 0)", string0);
      assertNotNull(string0);
  }
}
