/*
 * This file was automatically generated by EvoSuite
 * Thu May 07 10:59:40 GMT 2026
 */

package comp5111.assignment.cut;

import org.junit.Test;
import static org.junit.Assert.*;
import comp5111.assignment.cut.Subject;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Subject$GamePlayer_ESTest extends Subject$GamePlayer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertNotNull(subject_GamePlayer0);
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      
      Subject.GamePlayer subject_GamePlayer1 = subject0.new GamePlayer();
      assertNotNull(subject_GamePlayer1);
      assertTrue(subject_GamePlayer1.equals((Object)subject_GamePlayer0));
      assertEquals("Anonymous Player", subject_GamePlayer1.getName());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer1.toString());
      assertEquals(0, subject_GamePlayer1.getScore());
      
      boolean boolean0 = subject_GamePlayer0.equals(subject_GamePlayer1);
      assertTrue(boolean0);
      assertNotSame(subject_GamePlayer0, subject_GamePlayer1);
      assertNotSame(subject_GamePlayer1, subject_GamePlayer0);
      assertTrue(subject_GamePlayer0.equals((Object)subject_GamePlayer1));
      assertTrue(subject_GamePlayer1.equals((Object)subject_GamePlayer0));
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals("Anonymous Player", subject_GamePlayer1.getName());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer1.toString());
      assertEquals(0, subject_GamePlayer1.getScore());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertNotNull(subject_GamePlayer0);
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      
      boolean boolean0 = subject_GamePlayer0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertNotNull(subject_GamePlayer0);
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      
      boolean boolean0 = subject_GamePlayer0.equals(subject_GamePlayer0);
      assertTrue(boolean0);
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertNotNull(subject_GamePlayer0);
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      
      boolean boolean0 = subject_GamePlayer0.equals(subject0);
      assertFalse(boolean0);
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertNotNull(subject_GamePlayer0);
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      
      subject_GamePlayer0.resetScore();
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("B*D~");
      assertNotNull(subject_GamePlayer0);
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='B*D~', score=0}", subject_GamePlayer0.toString());
      assertEquals("B*D~", subject_GamePlayer0.getName());
      
      String string0 = subject_GamePlayer0.getName();
      assertEquals("B*D~", string0);
      assertNotNull(string0);
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='B*D~', score=0}", subject_GamePlayer0.toString());
      assertEquals("B*D~", subject_GamePlayer0.getName());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertNotNull(subject_GamePlayer0);
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      
      Subject.GamePlayer subject_GamePlayer1 = subject_GamePlayer0.clone();
      assertNotNull(subject_GamePlayer1);
      assertNotSame(subject_GamePlayer0, subject_GamePlayer1);
      assertNotSame(subject_GamePlayer1, subject_GamePlayer0);
      assertTrue(subject_GamePlayer1.equals((Object)subject_GamePlayer0));
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals("Anonymous Player", subject_GamePlayer1.getName());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer1.toString());
      assertEquals(0, subject_GamePlayer1.getScore());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertNotNull(subject_GamePlayer0);
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      
      subject_GamePlayer0.setScore(0);
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertNotNull(subject_GamePlayer0);
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      
      int int0 = subject_GamePlayer0.getScore();
      assertEquals(0, int0);
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertNotNull(subject_GamePlayer0);
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      
      String string0 = subject_GamePlayer0.toString();
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", string0);
      assertNotNull(string0);
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("<: r=LFdyfLI");
      assertNotNull(subject_GamePlayer0);
      assertEquals("GamePlayer{name='<: r=LFdyfLI', score=0}", subject_GamePlayer0.toString());
      assertEquals("<: r=LFdyfLI", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      
      subject_GamePlayer0.addScore((-22));
      assertEquals((-22), subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='<: r=LFdyfLI', score=-22}", subject_GamePlayer0.toString());
      assertEquals("<: r=LFdyfLI", subject_GamePlayer0.getName());
  }
}
