/*
 * This file was automatically generated by EvoSuite
 * Thu May 07 11:09:44 GMT 2026
 */

package comp5111.assignment.cut;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import comp5111.assignment.cut.Subject;
import java.nio.ByteBuffer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Subject$StringAlgorithms_ESTest extends Subject$StringAlgorithms_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padRight((String) null, (short) (-4), ']');
      assertEquals("", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padRight((String) null, (short)23, ']');
      assertEquals("]]]]]]]]]]]]]]]]]]]]]]]", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padRight("", (short)76, '(');
      assertEquals("((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padLeft((String) null, (short)0, ']');
      assertEquals("", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padLeft("", (short)76, '\u0014');
      assertEquals("\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014\u0014", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo(".");
      assertNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("");
      assertNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo((String) null);
      assertNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("*8WFttAl_)(_9Ie");
      assertEquals(4, intArray0.length);
      assertArrayEquals(new int[] {0, 0, 0, 0}, intArray0);
      assertNotNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      int int0 = Subject.StringAlgorithms.extractIntInStr("4");
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      int int0 = Subject.StringAlgorithms.extractIntInStr("");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("comp5111.assignment.cut.Subject$GamePlacecomp5111.assignment.cut.Subject$StringAlgorithms");
      assertNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      int int0 = Subject.StringAlgorithms.extractIntInStr((String) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("tmhh9xgX.0");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // Character t is neither a decimal digit number, decimal point, nor \"e\" notation exponential mark.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("HyE~T>+e3");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // Illegal embedded sign character
         //
         verifyException("java.math.BigInteger", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("0e9");
      assertEquals((byte)0, number0.byteValue());
      assertEquals((short)0, number0.shortValue());
      assertNotNull(number0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("3D");
      assertEquals((short)3, number0.shortValue());
      assertEquals((byte)3, number0.byteValue());
      assertNotNull(number0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("5d");
      assertEquals((byte)5, number0.byteValue());
      assertEquals((short)5, number0.shortValue());
      assertNotNull(number0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("A cZcH5B`MvddJ9JF");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("+fK_f");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("82l");
      assertEquals((byte)82, number0.byteValue());
      assertEquals((short)82, number0.shortValue());
      assertNotNull(number0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("\"=uge{L");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // \"=uge{L
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("^=?e");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // ^=?e
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("comp5111.assignment.cut.Subject$GameConfiguration");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // comp5111.assignment.cut.Subject$GameConfiguration
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber(">{%i)Eu&.J^96[8");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // >{%i)Eu&.J^96[8
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("9.L");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // 9.L
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("-0x%0KKfrA<Wt:(8\"sY");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"-%0KKfrA<Wt:(8\"sY\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("0x0");
      assertEquals(0, number0);
      assertNotNull(number0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("--");
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("D");
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("4");
      assertEquals((short)4, number0.shortValue());
      assertEquals((byte)4, number0.byteValue());
      assertNotNull(number0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("");
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber((String) null);
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("-l");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // -l
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("-2l");
      assertEquals((byte) (-2), number0.byteValue());
      assertEquals((short) (-2), number0.shortValue());
      assertNotNull(number0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      char[] charArray0 = new char[1];
      charArray0[0] = '&';
      String string0 = Subject.StringAlgorithms.parseToken("[H%D$m& s.[FK}8", charArray0);
      assertEquals("[H%D$m&", string0);
      assertEquals(1, charArray0.length);
      assertArrayEquals(new char[] {'&'}, charArray0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      char[] charArray0 = new char[1];
      String string0 = Subject.StringAlgorithms.parseToken("[H%D$m& s.[FK}8", charArray0);
      assertEquals("[H%D$m& s.[FK}8", string0);
      assertEquals(1, charArray0.length);
      assertArrayEquals(new char[] {'\u0000'}, charArray0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.strToBoolean("", "YQb", "YQb", "YQb");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("T", ".", "T", "T");
      assertFalse(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("", "YQb", "YQb", "");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null, "size of gameboard must be at least 3", (String) null, "size of gameboard must be at least 3");
      assertFalse(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null, (String) null, (String) null, "ai@?6!db");
      assertTrue(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null, (String) null, (String) null, (String) null);
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.strToBoolean((String) null, "#T", "#T", "#T");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("(x", "(x", "(x", "(x");
      assertTrue(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("--yGj");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("ftt3n");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("comp5111.assignment.cut.Subject$GamePlace");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("&=]1");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("tFOz");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Ts4 ");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("YQb");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("yyy");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Of+");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("oQ6");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("On");
      assertTrue(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("oQ");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("No");
      assertFalse(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("nO");
      assertFalse(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("N`");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("(");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("F");
      assertFalse(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("f");
      assertFalse(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("n");
      assertFalse(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("T");
      assertTrue(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("t");
      assertTrue(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Y");
      assertTrue(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("N");
      assertFalse(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("y");
      assertTrue(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null);
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("FaFLr");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      byte[] byteArray0 = new byte[25];
      Subject.StringAlgorithms.enlarge((-599), byteArray0, (byte)0);
      assertEquals(25, byteArray0.length);
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.enlarge(2888, byteArray0, 2888);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      byteArray0[0] = (byte) (-45);
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      assertEquals(0, byteBuffer0.arrayOffset());
      assertFalse(byteBuffer0.isDirect());
      assertEquals(1, byteBuffer0.limit());
      assertFalse(byteBuffer0.isReadOnly());
      assertEquals(1, byteBuffer0.capacity());
      assertEquals("java.nio.HeapByteBuffer[pos=0 lim=1 cap=1]", byteBuffer0.toString());
      assertEquals(0, byteBuffer0.position());
      assertTrue(byteBuffer0.hasArray());
      assertTrue(byteBuffer0.hasRemaining());
      assertEquals(1, byteBuffer0.remaining());
      assertEquals(1, byteArray0.length);
      assertArrayEquals(new byte[] {(byte) (-45)}, byteArray0);
      assertNotNull(byteBuffer0);
      
      StringBuilder stringBuilder0 = new StringBuilder("(x");
      assertEquals("(x", stringBuilder0.toString());
      assertNotNull(stringBuilder0);
      
      int int0 = Subject.StringAlgorithms.decodeOctets(1252, byteBuffer0, stringBuilder0);
      assertEquals(1254, int0);
      assertEquals(1, byteBuffer0.position());
      assertFalse(byteBuffer0.hasRemaining());
      assertEquals(0, byteBuffer0.arrayOffset());
      assertFalse(byteBuffer0.isDirect());
      assertEquals("java.nio.HeapByteBuffer[pos=1 lim=1 cap=1]", byteBuffer0.toString());
      assertEquals(1, byteBuffer0.limit());
      assertFalse(byteBuffer0.isReadOnly());
      assertEquals(1, byteBuffer0.capacity());
      assertTrue(byteBuffer0.hasArray());
      assertEquals(0, byteBuffer0.remaining());
      assertEquals("(x\uFFFD", stringBuilder0.toString());
      assertEquals(1, byteArray0.length);
      assertArrayEquals(new byte[] {(byte) (-45)}, byteArray0);
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      assertTrue(byteBuffer0.hasArray());
      assertEquals(1, byteBuffer0.capacity());
      assertEquals(1, byteBuffer0.limit());
      assertFalse(byteBuffer0.isDirect());
      assertEquals("java.nio.HeapByteBuffer[pos=0 lim=1 cap=1]", byteBuffer0.toString());
      assertEquals(0, byteBuffer0.position());
      assertEquals(0, byteBuffer0.arrayOffset());
      assertEquals(1, byteBuffer0.remaining());
      assertFalse(byteBuffer0.isReadOnly());
      assertTrue(byteBuffer0.hasRemaining());
      assertEquals(1, byteArray0.length);
      assertArrayEquals(new byte[] {(byte)0}, byteArray0);
      assertNotNull(byteBuffer0);
      
      StringBuilder stringBuilder0 = new StringBuilder("(x");
      assertEquals("(x", stringBuilder0.toString());
      assertNotNull(stringBuilder0);
      
      int int0 = Subject.StringAlgorithms.decodeOctets(1252, byteBuffer0, stringBuilder0);
      assertEquals(1254, int0);
      assertTrue(byteBuffer0.hasArray());
      assertEquals(1, byteBuffer0.capacity());
      assertEquals(1, byteBuffer0.limit());
      assertFalse(byteBuffer0.isDirect());
      assertEquals("java.nio.HeapByteBuffer[pos=0 lim=1 cap=1]", byteBuffer0.toString());
      assertEquals(0, byteBuffer0.position());
      assertEquals(0, byteBuffer0.arrayOffset());
      assertEquals(1, byteBuffer0.remaining());
      assertFalse(byteBuffer0.isReadOnly());
      assertTrue(byteBuffer0.hasRemaining());
      assertEquals("(x\u0000", stringBuilder0.toString());
      assertEquals(1, byteArray0.length);
      assertArrayEquals(new byte[] {(byte)0}, byteArray0);
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      ByteBuffer byteBuffer0 = ByteBuffer.allocate(121);
      assertFalse(byteBuffer0.isDirect());
      assertEquals(0, byteBuffer0.position());
      assertFalse(byteBuffer0.isReadOnly());
      assertTrue(byteBuffer0.hasArray());
      assertEquals(121, byteBuffer0.remaining());
      assertEquals(121, byteBuffer0.limit());
      assertTrue(byteBuffer0.hasRemaining());
      assertEquals(0, byteBuffer0.arrayOffset());
      assertEquals("java.nio.HeapByteBuffer[pos=0 lim=121 cap=121]", byteBuffer0.toString());
      assertEquals(121, byteBuffer0.capacity());
      assertNotNull(byteBuffer0);
      
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.decodeOctets(121, byteBuffer0, (StringBuilder) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "KCl,&]`3s+Wl(2LfDD";
      String[] stringArray1 = Subject.StringAlgorithms.trimArrayElements(stringArray0);
      assertFalse(stringArray1.equals((Object)stringArray0));
      assertEquals(1, stringArray0.length);
      assertEquals(1, stringArray1.length);
      assertNotNull(stringArray1);
      assertNotSame(stringArray0, stringArray1);
      assertNotSame(stringArray1, stringArray0);
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      String[] stringArray0 = new String[0];
      String[] stringArray1 = Subject.StringAlgorithms.trimArrayElements(stringArray0);
      assertFalse(stringArray1.equals((Object)stringArray0));
      assertEquals(0, stringArray0.length);
      assertEquals(0, stringArray1.length);
      assertNotNull(stringArray1);
      assertNotSame(stringArray0, stringArray1);
      assertNotSame(stringArray1, stringArray0);
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      String[] stringArray0 = new String[7];
      String[] stringArray1 = Subject.StringAlgorithms.trimArrayElements(stringArray0);
      assertFalse(stringArray1.equals((Object)stringArray0));
      assertEquals(7, stringArray0.length);
      assertEquals(7, stringArray1.length);
      assertNotNull(stringArray1);
      assertNotSame(stringArray0, stringArray1);
      assertNotSame(stringArray1, stringArray0);
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      String[] stringArray0 = Subject.StringAlgorithms.trimArrayElements((String[]) null);
      assertEquals(0, stringArray0.length);
      assertNotNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test80()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("-->QrG2zo$xEq'H$'K", "Puh|D@Wpvt*d[`");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test81()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("->&", "Puh|D@Wpvt*d[`");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test82()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("-->QrG2zo$xEq'H$'K", (String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test83()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("(x", "(x");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test84()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase((String) null, (String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test85()  throws Throwable  {
      Subject.StringAlgorithms subject_StringAlgorithms0 = new Subject.StringAlgorithms();
      assertNotNull(subject_StringAlgorithms0);
  }
}
