/*
 * This file was automatically generated by EvoSuite
 * Thu May 07 11:31:00 GMT 2026
 */

package comp5111.assignment.cut;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import comp5111.assignment.cut.Subject;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Subject$GameConfiguration_ESTest extends Subject$GameConfiguration_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(3, subject_GameConfiguration0.getSize());
      
      subject_GameConfiguration0.clearInitialBoard();
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(3, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, 2);
      assertNotNull(subject_GamePlace0);
      assertEquals(2, subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals("(2, 2)", subject_GamePlace0.toString());
      
      subject_GamePlace0.y(0);
      assertEquals(0, subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals("(2, 0)", subject_GamePlace0.toString());
      
      subject_GamePlace0.x(0);
      assertEquals("(0, 0)", subject_GamePlace0.toString());
      assertEquals(0, subject_GamePlace0.y());
      assertEquals(0, subject_GamePlace0.x());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player A");
      assertNotNull(subject_GamePlayer0);
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals("Player A", subject_GamePlayer0.getName());
      
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals("(0, 0)", subject_GamePlace0.toString());
      assertEquals(0, subject_GamePlace0.y());
      assertEquals(0, subject_GamePlace0.x());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals("Player A", subject_GamePlayer0.getName());
      
      boolean boolean0 = subject_GameConfiguration0.isBoardFull();
      assertFalse(boolean0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, 1);
      assertNotNull(subject_GamePlace0);
      assertEquals("(2, 1)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player A");
      assertNotNull(subject_GamePlayer0);
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals("Player A", subject_GamePlayer0.getName());
      
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertEquals("(2, 1)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals("Player A", subject_GamePlayer0.getName());
      
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getPlacesOfPlayer((Subject.GamePlayer) null);
      assertFalse(list0.contains(subject_GamePlace0));
      assertNotNull(list0);
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertTrue(list0.isEmpty());
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      assertNotNull(subject_GameConfiguration0);
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(25, 1);
      assertNotNull(subject_GamePlace0);
      assertEquals(25, subject_GamePlace0.x());
      assertEquals(1, subject_GamePlace0.y());
      assertEquals("(25, 1)", subject_GamePlace0.toString());
      
      subject_GamePlace0.x(1);
      assertEquals("(1, 1)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.x());
      assertEquals(1, subject_GamePlace0.y());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player A");
      assertNotNull(subject_GamePlayer0);
      assertEquals("Player A", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals("(1, 1)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.x());
      assertEquals(1, subject_GamePlace0.y());
      assertEquals("Player A", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getPlacesOfPlayer(subject_GamePlayer0);
      assertTrue(list0.contains(subject_GamePlace0));
      assertNotNull(list0);
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals("Player A", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals(1, list0.size());
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, 1);
      assertNotNull(subject_GamePlace0);
      assertEquals(1, subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals("(2, 1)", subject_GamePlace0.toString());
      
      subject_GamePlace0.x(0);
      assertEquals(0, subject_GamePlace0.x());
      assertEquals(1, subject_GamePlace0.y());
      assertEquals("(0, 1)", subject_GamePlace0.toString());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player A");
      assertNotNull(subject_GamePlayer0);
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals("Player A", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(0, subject_GamePlace0.x());
      assertEquals(1, subject_GamePlace0.y());
      assertEquals("(0, 1)", subject_GamePlace0.toString());
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals("Player A", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      
      boolean boolean0 = subject_GameConfiguration0.isBoardSymmetric();
      assertFalse(boolean0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      assertNotNull(subject_GameConfiguration0);
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, 1);
      assertNotNull(subject_GamePlace0);
      assertEquals("(2, 1)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player A");
      assertNotNull(subject_GamePlayer0);
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Player A", subject_GamePlayer0.getName());
      
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals("(2, 1)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Player A", subject_GamePlayer0.getName());
      
      boolean boolean0 = subject_GameConfiguration0.isBoardSymmetric();
      assertFalse(boolean0);
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      assertNotNull(subject_GameConfiguration0);
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(25, 1);
      assertNotNull(subject_GamePlace0);
      assertEquals(25, subject_GamePlace0.x());
      assertEquals("(25, 1)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.y());
      
      subject_GamePlace0.x(1);
      assertEquals("(1, 1)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.x());
      assertEquals(1, subject_GamePlace0.y());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player A");
      assertNotNull(subject_GamePlayer0);
      assertEquals("Player A", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals("(1, 1)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.x());
      assertEquals(1, subject_GamePlace0.y());
      assertEquals("Player A", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      
      boolean boolean0 = subject_GameConfiguration0.isBoardSymmetric();
      assertTrue(boolean0);
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, 25);
      assertNotNull(subject_GamePlace0);
      assertEquals("(2, 25)", subject_GamePlace0.toString());
      assertEquals(25, subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
      
      subject_GamePlace0.y(2);
      assertEquals("(2, 2)", subject_GamePlace0.toString());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player A");
      assertNotNull(subject_GamePlayer0);
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Player A", subject_GamePlayer0.getName());
      
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals("(2, 2)", subject_GamePlace0.toString());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Player A", subject_GamePlayer0.getName());
      
      int[] intArray0 = subject_GameConfiguration0.countPiecesPerPlayer();
      assertArrayEquals(new int[] {1, 0}, intArray0);
      assertNotNull(intArray0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(2, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(25, subject_GameConfiguration0.getSize());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, 25);
      assertNotNull(subject_GamePlace0);
      assertEquals(2, subject_GamePlace0.x());
      assertEquals(25, subject_GamePlace0.y());
      assertEquals("(2, 25)", subject_GamePlace0.toString());
      
      subject_GamePlace0.y(2);
      assertEquals(2, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      assertEquals("(2, 2)", subject_GamePlace0.toString());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player A");
      assertNotNull(subject_GamePlayer0);
      assertEquals("Player A", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      assertEquals("(2, 2)", subject_GamePlace0.toString());
      assertEquals("Player A", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertTrue(boolean0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      assertEquals("(2, 2)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-2909), (-2909));
      assertNotNull(subject_GamePlace0);
      assertEquals("(-2909, -2909)", subject_GamePlace0.toString());
      assertEquals((-2909), subject_GamePlace0.x());
      assertEquals((-2909), subject_GamePlace0.y());
      
      subject_GamePlace0.y(3);
      assertEquals("(-2909, 3)", subject_GamePlace0.toString());
      assertEquals(3, subject_GamePlace0.y());
      assertEquals((-2909), subject_GamePlace0.x());
      
      subject_GamePlace0.x(2);
      assertEquals(2, subject_GamePlace0.x());
      assertEquals(3, subject_GamePlace0.y());
      assertEquals("(2, 3)", subject_GamePlace0.toString());
      
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertTrue(boolean0);
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals(3, subject_GamePlace0.y());
      assertEquals("(2, 3)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(3, subject_GameConfiguration0.getSize());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-2909), (-2909));
      assertNotNull(subject_GamePlace0);
      assertEquals((-2909), subject_GamePlace0.y());
      assertEquals((-2909), subject_GamePlace0.x());
      assertEquals("(-2909, -2909)", subject_GamePlace0.toString());
      
      subject_GamePlace0.x(2);
      assertEquals("(2, -2909)", subject_GamePlace0.toString());
      assertEquals((-2909), subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
      
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertTrue(boolean0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertEquals("(2, -2909)", subject_GamePlace0.toString());
      assertEquals((-2909), subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(3, 3);
      assertNotNull(subject_GamePlace0);
      assertEquals(3, subject_GamePlace0.y());
      assertEquals(3, subject_GamePlace0.x());
      assertEquals("(3, 3)", subject_GamePlace0.toString());
      
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertTrue(boolean0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(3, subject_GamePlace0.y());
      assertEquals(3, subject_GamePlace0.x());
      assertEquals("(3, 3)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      assertNotNull(subject_GameConfiguration0);
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, 2);
      assertNotNull(subject_GamePlace0);
      assertEquals(2, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      assertEquals("(2, 2)", subject_GamePlace0.toString());
      
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertFalse(boolean0);
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      assertEquals("(2, 2)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-2909), (-2909));
      assertNotNull(subject_GamePlace0);
      assertEquals((-2909), subject_GamePlace0.y());
      assertEquals("(-2909, -2909)", subject_GamePlace0.toString());
      assertEquals((-2909), subject_GamePlace0.x());
      
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertTrue(boolean0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals((-2909), subject_GamePlace0.y());
      assertEquals("(-2909, -2909)", subject_GamePlace0.toString());
      assertEquals((-2909), subject_GamePlace0.x());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(25, subject_GameConfiguration0.getSize());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, 25);
      assertNotNull(subject_GamePlace0);
      assertEquals(25, subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals("(2, 25)", subject_GamePlace0.toString());
      
      subject_GamePlace0.y(2);
      assertEquals("(2, 2)", subject_GamePlace0.toString());
      assertEquals(2, subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player A");
      assertNotNull(subject_GamePlayer0);
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals("Player A", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertEquals("(2, 2)", subject_GamePlace0.toString());
      assertEquals(2, subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals("Player A", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getEmptyPlaces();
      assertFalse(list0.contains(subject_GamePlace0));
      assertNotNull(list0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertFalse(list0.isEmpty());
      assertEquals(623, list0.size());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      String string0 = subject_GameConfiguration0.toString();
      assertNotNull(string0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, 3);
      assertNotNull(subject_GamePlace0);
      assertEquals(2, subject_GamePlace0.x());
      assertEquals(3, subject_GamePlace0.y());
      assertEquals("(2, 3)", subject_GamePlace0.toString());
      
      subject_GamePlace0.y(2);
      assertEquals(2, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      assertEquals("(2, 2)", subject_GamePlace0.toString());
      
      Subject.GamePlayer subject_GamePlayer0 = subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
      assertNull(subject_GamePlayer0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      assertEquals("(2, 2)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, (-649));
      assertNotNull(subject_GamePlace0);
      assertEquals("(2, -649)", subject_GamePlace0.toString());
      assertEquals((-649), subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      assertNotNull(subject_GameConfiguration0);
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(25, 25);
      assertNotNull(subject_GamePlace0);
      assertEquals("(25, 25)", subject_GamePlace0.toString());
      assertEquals(25, subject_GamePlace0.x());
      assertEquals(25, subject_GamePlace0.y());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 3);
      assertNotNull(subject_GamePlace0);
      assertEquals(3, subject_GamePlace0.y());
      assertEquals("(1, 3)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.x());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-2909), (-2909));
      assertNotNull(subject_GamePlace0);
      assertEquals((-2909), subject_GamePlace0.y());
      assertEquals("(-2909, -2909)", subject_GamePlace0.toString());
      assertEquals((-2909), subject_GamePlace0.x());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(3, subject_GameConfiguration0.getSize());
      
      Subject.GamePlayer[][] subject_GamePlayerArray0 = subject_GameConfiguration0.getInitialBoard();
      assertNotNull(subject_GamePlayerArray0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertEquals(3, subject_GamePlayerArray0.length);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GameConfiguration subject_GameConfiguration1 = subject_GameConfiguration0.clone();
      assertNotSame(subject_GameConfiguration0, subject_GameConfiguration1);
      assertNotSame(subject_GameConfiguration1, subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration1.equals((Object)subject_GameConfiguration0));
      assertNotNull(subject_GameConfiguration1);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertFalse(subject_GameConfiguration1.isBoardFull());
      assertTrue(subject_GameConfiguration1.isBoardSymmetric());
      assertEquals(3, subject_GameConfiguration1.getSize());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-2909), (-2909));
      assertNotNull(subject_GamePlace0);
      assertEquals((-2909), subject_GamePlace0.x());
      assertEquals((-2909), subject_GamePlace0.y());
      assertEquals("(-2909, -2909)", subject_GamePlace0.toString());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player B");
      assertNotNull(subject_GamePlayer0);
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Player B", subject_GamePlayer0.getName());
      
      subject_GamePlace0.x(1);
      assertEquals((-2909), subject_GamePlace0.y());
      assertEquals(1, subject_GamePlace0.x());
      assertEquals("(1, -2909)", subject_GamePlace0.toString());
      
      subject_GamePlace0.y(1);
      assertEquals("(1, 1)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.y());
      assertEquals(1, subject_GamePlace0.x());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // piece cannot be put at central place initially
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(3, subject_GameConfiguration0.getSize());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-2909), (-2909));
      assertNotNull(subject_GamePlace0);
      assertEquals((-2909), subject_GamePlace0.y());
      assertEquals("(-2909, -2909)", subject_GamePlace0.toString());
      assertEquals((-2909), subject_GamePlace0.x());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player B");
      assertNotNull(subject_GamePlayer0);
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Player B", subject_GamePlayer0.getName());
      
      subject_GamePlace0.x(1);
      assertEquals((-2909), subject_GamePlace0.y());
      assertEquals(1, subject_GamePlace0.x());
      assertEquals("(1, -2909)", subject_GamePlace0.toString());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // the place(1, -2909) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(25, subject_GameConfiguration0.getSize());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, 25);
      assertNotNull(subject_GamePlace0);
      assertEquals("(2, 25)", subject_GamePlace0.toString());
      assertEquals(25, subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
      
      subject_GamePlace0.y(2);
      assertEquals("(2, 2)", subject_GamePlace0.toString());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player A");
      assertNotNull(subject_GamePlayer0);
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals("Player A", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertEquals("(2, 2)", subject_GamePlace0.toString());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals("Player A", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      
      String string0 = subject_GameConfiguration0.toString();
      assertNotNull(string0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(25, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player B");
      assertNotNull(subject_GamePlayer0);
      assertEquals("Player B", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(3, 3);
      assertNotNull(subject_GamePlace0);
      assertEquals(3, subject_GamePlace0.y());
      assertEquals(3, subject_GamePlace0.x());
      assertEquals("(3, 3)", subject_GamePlace0.toString());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // the place(3, 3) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(25, subject_GameConfiguration0.getSize());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertNotNull(subject_GamePlayer0);
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(25, 25);
      assertNotNull(subject_GamePlace0);
      assertEquals("(25, 25)", subject_GamePlace0.toString());
      assertEquals(25, subject_GamePlace0.y());
      assertEquals(25, subject_GamePlace0.x());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // the player of the piece is unknown
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-2909), (-2909));
      assertNotNull(subject_GamePlace0);
      assertEquals((-2909), subject_GamePlace0.x());
      assertEquals((-2909), subject_GamePlace0.y());
      assertEquals("(-2909, -2909)", subject_GamePlace0.toString());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player B");
      assertNotNull(subject_GamePlayer0);
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals("Player B", subject_GamePlayer0.getName());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // the place(-2909, -2909) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, 25);
      assertNotNull(subject_GamePlace0);
      assertEquals(2, subject_GamePlace0.x());
      assertEquals("(2, 25)", subject_GamePlace0.toString());
      assertEquals(25, subject_GamePlace0.y());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player A");
      assertNotNull(subject_GamePlayer0);
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals("Player A", subject_GamePlayer0.getName());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // the place(2, 25) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[1];
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(3, subject_GamePlayerArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // there must be exactly two players
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(243);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard is at most 25
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(1762);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be an odd number
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be at least 3
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      int int0 = subject_GameConfiguration0.getSize();
      assertEquals(3, int0);
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlayer[] subject_GamePlayerArray0 = subject_GameConfiguration0.getPlayers();
      assertNotNull(subject_GamePlayerArray0);
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(2, subject_GamePlayerArray0.length);
  }
}
