/*
 * This file was automatically generated by EvoSuite
 * Thu May 07 11:31:01 GMT 2026
 */

package comp5111.assignment.cut;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import comp5111.assignment.cut.Subject;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Subject$DateTimeAlgorithms_ESTest extends Subject$DateTimeAlgorithms_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("0003-03-31", "0003-03-31");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween((-2297), 1, (-819), 1);
      assertEquals(17736, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(12, 11, (-1737), (-1641));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(1152, 1152, 13, (-1));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(1, 1, (-1), 31);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween((-1999), (-1999), (-1999), (-2059));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth(5328, (-1));
      assertEquals("(invalid)", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth((-1), 8);
      assertEquals("-001-08-31", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth(1295, 8);
      assertEquals("1295-08-01", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth((-1), 2039);
      assertEquals("(invalid)", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth(10, 0);
      assertEquals("(invalid)", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(3038, 3, 4, 3038, 6, 4);
      assertEquals(1, list0.size());
      assertFalse(list0.isEmpty());
      assertNotNull(list0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(1644, (-2889), 1);
      assertEquals("(invalid)", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("nTwn`'w-#-J&{(E=Dp", "there must be exactly two players");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("", "");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysInYear(0);
      assertEquals(366, int0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysInYear((-255));
      assertEquals(365, int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr((-1737));
      assertEquals("(invalid)", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(12);
      assertEquals("Dec", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(11);
      assertEquals("Nov", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(10);
      assertEquals("Oct", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(9);
      assertEquals("Sep", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(1295, 8, 11);
      assertEquals("11th Aug 1295", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(7);
      assertEquals("Jul", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(6);
      assertEquals("Jun", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(4);
      assertEquals("Apr", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(3);
      assertEquals("Mar", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(2);
      assertEquals("Feb", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(5);
      assertEquals("May", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(1);
      assertEquals("Jan", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Dec");
      assertEquals(12, int0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("7 M");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Oct");
      assertEquals(10, int0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Aug");
      assertEquals(8, int0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jul");
      assertEquals(7, int0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jun");
      assertEquals(6, int0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("May");
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Apr");
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Mar");
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Feb");
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jan");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Nov");
      assertEquals(11, int0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month((String) null);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(8);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(4);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(404);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(11);
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter((-1));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(493);
      assertEquals("(invalid)", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(2);
      assertEquals("2nd", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(31);
      assertEquals("31st", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(426);
      assertEquals("(invalid)", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr((-830));
      assertEquals("(invalid)", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(426);
      assertEquals("7 M", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(3600L);
      assertEquals("1 H", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(86400L);
      assertEquals("1 D", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(4289895);
      assertEquals("7 W", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(86400000L);
      assertEquals("3 Y", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(0L);
      assertEquals("0 S", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      boolean boolean0 = Subject.DateTimeAlgorithms.judgeLeapYear(2200);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.calcDaysInMonth(0, 2);
      assertEquals(29, int0);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(2168, 10, 4012, 3, (-1), (-1));
      assertEquals(0, list0.size());
      assertTrue(list0.isEmpty());
      assertNotNull(list0);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(12, 2168, 3, 12, 1870, 12);
      assertEquals(0, list0.size());
      assertTrue(list0.isEmpty());
      assertNotNull(list0);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween((-1), 9, (-1), 1482, (-1), (-1));
      assertTrue(list0.isEmpty());
      assertEquals(0, list0.size());
      assertNotNull(list0);
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      // Undeclared exception!
      Subject.DateTimeAlgorithms.listDatesBetween(1115, 4, 4, 4, 4, 4);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween((-284), 2, (-1764), 2, 1, 9);
      assertTrue(list0.isEmpty());
      assertEquals(0, list0.size());
      assertNotNull(list0);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(2, 2, 2, (-1477), (-177), (-177));
      assertEquals(0, list0.size());
      assertTrue(list0.isEmpty());
      assertNotNull(list0);
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.calcDaysInMonth(573, 862);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDates(11, 10, 10, 10, 11, 10);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.DateTimeAlgorithms.daysBetweenDates(7, 7, 7, (-2620), 7, (-2620));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid date
         //
         verifyException("comp5111.assignment.cut.Subject$DateTimeAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      Subject.DateTimeAlgorithms subject_DateTimeAlgorithms0 = new Subject.DateTimeAlgorithms();
      assertNotNull(subject_DateTimeAlgorithms0);
  }
}
