/*
 * This file was automatically generated by EvoSuite
 * Thu May 07 11:21:10 GMT 2026
 */

package comp5111.assignment.cut;

import org.junit.Test;
import static org.junit.Assert.*;
import comp5111.assignment.cut.Subject;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Subject$GamePlayer_ESTest extends Subject$GamePlayer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertNotNull(subject_GamePlayer0);
      
      boolean boolean0 = subject_GamePlayer0.equals((Object) null);
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertNotNull(subject_GamePlayer0);
      
      boolean boolean0 = subject_GamePlayer0.equals(subject_GamePlayer0);
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertNotNull(subject_GamePlayer0);
      
      boolean boolean0 = subject_GamePlayer0.equals(subject0);
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertNotNull(subject_GamePlayer0);
      
      subject_GamePlayer0.addScore(1546);
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Anonymous Player', score=1546}", subject_GamePlayer0.toString());
      assertEquals(1546, subject_GamePlayer0.getScore());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertNotNull(subject_GamePlayer0);
      
      subject_GamePlayer0.resetScore();
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertNotNull(subject_GamePlayer0);
      
      String string0 = subject_GamePlayer0.getName();
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertNotNull(string0);
      assertEquals("Anonymous Player", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertNotNull(subject_GamePlayer0);
      
      subject_GamePlayer0.setScore(447);
      assertEquals("GamePlayer{name='Anonymous Player', score=447}", subject_GamePlayer0.toString());
      assertEquals(447, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertNotNull(subject_GamePlayer0);
      
      int int0 = subject_GamePlayer0.getScore();
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertNotNull(subject_GamePlayer0);
      
      String string0 = subject_GamePlayer0.toString();
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertNotNull(string0);
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", string0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertNotNull(subject_GamePlayer0);
      
      Subject.GamePlayer subject_GamePlayer1 = subject_GamePlayer0.clone();
      assertTrue(subject_GamePlayer1.equals((Object)subject_GamePlayer0));
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer1.toString());
      assertEquals("Anonymous Player", subject_GamePlayer1.getName());
      assertEquals(0, subject_GamePlayer1.getScore());
      assertNotSame(subject_GamePlayer0, subject_GamePlayer1);
      assertNotSame(subject_GamePlayer1, subject_GamePlayer0);
      assertNotNull(subject_GamePlayer1);
      
      boolean boolean0 = subject_GamePlayer1.equals(subject_GamePlayer0);
      assertTrue(subject_GamePlayer0.equals((Object)subject_GamePlayer1));
      assertTrue(subject_GamePlayer1.equals((Object)subject_GamePlayer0));
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer1.toString());
      assertEquals("Anonymous Player", subject_GamePlayer1.getName());
      assertEquals(0, subject_GamePlayer1.getScore());
      assertNotSame(subject_GamePlayer0, subject_GamePlayer1);
      assertNotSame(subject_GamePlayer1, subject_GamePlayer0);
      assertTrue(boolean0);
  }
}
