/*
 * This file was automatically generated by EvoSuite
 * Thu May 07 11:21:05 GMT 2026
 */

package comp5111.assignment.cut;

import org.junit.Test;
import static org.junit.Assert.*;
import comp5111.assignment.cut.Subject;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Subject$GamePlace_ESTest extends Subject$GamePlace_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-3292), 31);
      assertNotNull(subject_GamePlace0);
      assertEquals(31, subject_GamePlace0.y());
      assertEquals((-3292), subject_GamePlace0.x());
      assertEquals("(-3292, 31)", subject_GamePlace0.toString());
      
      int int0 = subject_GamePlace0.manhattanDistance((Subject.GamePlace) null);
      assertEquals((-1), int0);
      assertEquals(31, subject_GamePlace0.y());
      assertEquals((-3292), subject_GamePlace0.x());
      assertEquals("(-3292, 31)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 0);
      assertNotNull(subject_GamePlace0);
      assertEquals("(0, 0)", subject_GamePlace0.toString());
      assertEquals(0, subject_GamePlace0.x());
      assertEquals(0, subject_GamePlace0.y());
      
      int int0 = subject_GamePlace0.manhattanDistance(subject_GamePlace0);
      assertEquals(0, int0);
      assertEquals("(0, 0)", subject_GamePlace0.toString());
      assertEquals(0, subject_GamePlace0.x());
      assertEquals(0, subject_GamePlace0.y());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 1);
      assertNotNull(subject_GamePlace0);
      assertEquals(1, subject_GamePlace0.x());
      assertEquals("(1, 1)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.y());
      
      Subject.GamePlace subject_GamePlace1 = subject0.new GamePlace(1, 1);
      assertNotNull(subject_GamePlace1);
      assertEquals(1, subject_GamePlace1.y());
      assertEquals(1, subject_GamePlace1.x());
      assertEquals("(1, 1)", subject_GamePlace1.toString());
      assertTrue(subject_GamePlace1.equals((Object)subject_GamePlace0));
      
      subject_GamePlace1.y(0);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals("(1, 0)", subject_GamePlace1.toString());
      assertEquals(0, subject_GamePlace1.y());
      assertEquals(1, subject_GamePlace1.x());
      assertFalse(subject_GamePlace1.equals((Object)subject_GamePlace0));
      
      boolean boolean0 = subject_GamePlace0.isAdjacent(subject_GamePlace1);
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertTrue(boolean0);
      assertEquals(1, subject_GamePlace0.x());
      assertEquals("(1, 1)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.y());
      assertEquals("(1, 0)", subject_GamePlace1.toString());
      assertEquals(0, subject_GamePlace1.y());
      assertEquals(1, subject_GamePlace1.x());
      assertFalse(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertFalse(subject_GamePlace1.equals((Object)subject_GamePlace0));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-3292), 31);
      assertNotNull(subject_GamePlace0);
      assertEquals(31, subject_GamePlace0.y());
      assertEquals((-3292), subject_GamePlace0.x());
      assertEquals("(-3292, 31)", subject_GamePlace0.toString());
      
      boolean boolean0 = subject_GamePlace0.isAdjacent((Subject.GamePlace) null);
      assertFalse(boolean0);
      assertEquals(31, subject_GamePlace0.y());
      assertEquals((-3292), subject_GamePlace0.x());
      assertEquals("(-3292, 31)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-3292), 31);
      assertNotNull(subject_GamePlace0);
      assertEquals(31, subject_GamePlace0.y());
      assertEquals((-3292), subject_GamePlace0.x());
      assertEquals("(-3292, 31)", subject_GamePlace0.toString());
      
      boolean boolean0 = subject_GamePlace0.isAdjacent(subject_GamePlace0);
      assertFalse(boolean0);
      assertEquals(31, subject_GamePlace0.y());
      assertEquals((-3292), subject_GamePlace0.x());
      assertEquals("(-3292, 31)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(667, 667);
      assertNotNull(subject_GamePlace0);
      assertEquals("(667, 667)", subject_GamePlace0.toString());
      assertEquals(667, subject_GamePlace0.x());
      assertEquals(667, subject_GamePlace0.y());
      
      Subject.GamePlace subject_GamePlace1 = subject0.new GamePlace(667, 667);
      assertNotNull(subject_GamePlace1);
      assertEquals("(667, 667)", subject_GamePlace1.toString());
      assertEquals(667, subject_GamePlace1.x());
      assertEquals(667, subject_GamePlace1.y());
      assertTrue(subject_GamePlace1.equals((Object)subject_GamePlace0));
      
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace1);
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertTrue(boolean0);
      assertEquals("(667, 667)", subject_GamePlace0.toString());
      assertEquals(667, subject_GamePlace0.x());
      assertEquals(667, subject_GamePlace0.y());
      assertEquals("(667, 667)", subject_GamePlace1.toString());
      assertEquals(667, subject_GamePlace1.x());
      assertEquals(667, subject_GamePlace1.y());
      assertTrue(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertTrue(subject_GamePlace1.equals((Object)subject_GamePlace0));
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(667, 667);
      assertNotNull(subject_GamePlace0);
      assertEquals("(667, 667)", subject_GamePlace0.toString());
      assertEquals(667, subject_GamePlace0.y());
      assertEquals(667, subject_GamePlace0.x());
      
      Subject.GamePlace subject_GamePlace1 = subject0.new GamePlace(2563, 667);
      assertNotNull(subject_GamePlace1);
      assertEquals(667, subject_GamePlace1.y());
      assertEquals("(2563, 667)", subject_GamePlace1.toString());
      assertEquals(2563, subject_GamePlace1.x());
      assertFalse(subject_GamePlace1.equals((Object)subject_GamePlace0));
      
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace1);
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertFalse(boolean0);
      assertEquals("(667, 667)", subject_GamePlace0.toString());
      assertEquals(667, subject_GamePlace0.y());
      assertEquals(667, subject_GamePlace0.x());
      assertEquals(667, subject_GamePlace1.y());
      assertEquals("(2563, 667)", subject_GamePlace1.toString());
      assertEquals(2563, subject_GamePlace1.x());
      assertFalse(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertFalse(subject_GamePlace1.equals((Object)subject_GamePlace0));
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1100, 179);
      assertNotNull(subject_GamePlace0);
      assertEquals("(1100, 179)", subject_GamePlace0.toString());
      assertEquals(1100, subject_GamePlace0.x());
      assertEquals(179, subject_GamePlace0.y());
      
      Subject.GamePlace subject_GamePlace1 = subject0.new GamePlace(1100, 1100);
      assertNotNull(subject_GamePlace1);
      assertEquals(1100, subject_GamePlace1.x());
      assertEquals(1100, subject_GamePlace1.y());
      assertEquals("(1100, 1100)", subject_GamePlace1.toString());
      assertFalse(subject_GamePlace1.equals((Object)subject_GamePlace0));
      
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace1);
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertFalse(boolean0);
      assertEquals("(1100, 179)", subject_GamePlace0.toString());
      assertEquals(1100, subject_GamePlace0.x());
      assertEquals(179, subject_GamePlace0.y());
      assertEquals(1100, subject_GamePlace1.x());
      assertEquals(1100, subject_GamePlace1.y());
      assertEquals("(1100, 1100)", subject_GamePlace1.toString());
      assertFalse(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertFalse(subject_GamePlace1.equals((Object)subject_GamePlace0));
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(667, 667);
      assertNotNull(subject_GamePlace0);
      assertEquals(667, subject_GamePlace0.y());
      assertEquals("(667, 667)", subject_GamePlace0.toString());
      assertEquals(667, subject_GamePlace0.x());
      
      boolean boolean0 = subject_GamePlace0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals(667, subject_GamePlace0.y());
      assertEquals("(667, 667)", subject_GamePlace0.toString());
      assertEquals(667, subject_GamePlace0.x());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(667, 667);
      assertNotNull(subject_GamePlace0);
      assertEquals(667, subject_GamePlace0.x());
      assertEquals("(667, 667)", subject_GamePlace0.toString());
      assertEquals(667, subject_GamePlace0.y());
      
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace0);
      assertTrue(boolean0);
      assertEquals(667, subject_GamePlace0.x());
      assertEquals("(667, 667)", subject_GamePlace0.toString());
      assertEquals(667, subject_GamePlace0.y());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 1);
      assertNotNull(subject_GamePlace0);
      assertEquals(1, subject_GamePlace0.y());
      assertEquals(1, subject_GamePlace0.x());
      assertEquals("(1, 1)", subject_GamePlace0.toString());
      
      boolean boolean0 = subject_GamePlace0.equals(subject0);
      assertFalse(boolean0);
      assertEquals(1, subject_GamePlace0.y());
      assertEquals(1, subject_GamePlace0.x());
      assertEquals("(1, 1)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(667, 667);
      assertNotNull(subject_GamePlace0);
      assertEquals("(667, 667)", subject_GamePlace0.toString());
      assertEquals(667, subject_GamePlace0.x());
      assertEquals(667, subject_GamePlace0.y());
      
      subject_GamePlace0.x(667);
      assertEquals("(667, 667)", subject_GamePlace0.toString());
      assertEquals(667, subject_GamePlace0.x());
      assertEquals(667, subject_GamePlace0.y());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-3292), 31);
      assertNotNull(subject_GamePlace0);
      assertEquals("(-3292, 31)", subject_GamePlace0.toString());
      assertEquals((-3292), subject_GamePlace0.x());
      assertEquals(31, subject_GamePlace0.y());
      
      subject_GamePlace0.hashCode();
      assertEquals("(-3292, 31)", subject_GamePlace0.toString());
      assertEquals((-3292), subject_GamePlace0.x());
      assertEquals(31, subject_GamePlace0.y());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-3292), 31);
      assertNotNull(subject_GamePlace0);
      assertEquals("(-3292, 31)", subject_GamePlace0.toString());
      assertEquals(31, subject_GamePlace0.y());
      assertEquals((-3292), subject_GamePlace0.x());
      
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertNotNull(subject_GamePlace1);
      assertEquals("(-3292, 31)", subject_GamePlace0.toString());
      assertEquals(31, subject_GamePlace0.y());
      assertEquals((-3292), subject_GamePlace0.x());
      assertEquals(31, subject_GamePlace1.y());
      assertEquals((-3292), subject_GamePlace1.x());
      assertEquals("(-3292, 31)", subject_GamePlace1.toString());
      assertTrue(subject_GamePlace1.equals((Object)subject_GamePlace0));
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 1);
      assertNotNull(subject_GamePlace0);
      assertEquals(1, subject_GamePlace0.y());
      assertEquals("(1, 1)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.x());
      
      int int0 = subject_GamePlace0.x();
      assertEquals(1, int0);
      assertEquals(1, subject_GamePlace0.y());
      assertEquals("(1, 1)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.x());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-3292), 31);
      assertNotNull(subject_GamePlace0);
      assertEquals("(-3292, 31)", subject_GamePlace0.toString());
      assertEquals((-3292), subject_GamePlace0.x());
      assertEquals(31, subject_GamePlace0.y());
      
      int int0 = subject_GamePlace0.y();
      assertEquals(31, int0);
      assertEquals("(-3292, 31)", subject_GamePlace0.toString());
      assertEquals((-3292), subject_GamePlace0.x());
      assertEquals(31, subject_GamePlace0.y());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-3292), 31);
      assertNotNull(subject_GamePlace0);
      assertEquals("(-3292, 31)", subject_GamePlace0.toString());
      assertEquals((-3292), subject_GamePlace0.x());
      assertEquals(31, subject_GamePlace0.y());
      
      String string0 = subject_GamePlace0.toString();
      assertEquals("(-3292, 31)", string0);
      assertNotNull(string0);
      assertEquals("(-3292, 31)", subject_GamePlace0.toString());
      assertEquals((-3292), subject_GamePlace0.x());
      assertEquals(31, subject_GamePlace0.y());
  }
}
