/*
 * This file was automatically generated by EvoSuite
 * Thu May 07 11:20:02 GMT 2026
 */

package comp5111.assignment.cut;

import org.junit.Test;
import static org.junit.Assert.*;
import comp5111.assignment.cut.Subject;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Subject$GamePlace_ESTest extends Subject$GamePlace_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1702, 2686);
      assertNotNull(subject_GamePlace0);
      assertEquals(1702, subject_GamePlace0.x());
      assertEquals(2686, subject_GamePlace0.y());
      assertEquals("(1702, 2686)", subject_GamePlace0.toString());
      
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      assertTrue(subject_GamePlace1.equals((Object)subject_GamePlace0));
      assertNotNull(subject_GamePlace1);
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals(1702, subject_GamePlace0.x());
      assertEquals(2686, subject_GamePlace0.y());
      assertEquals("(1702, 2686)", subject_GamePlace0.toString());
      assertEquals(2686, subject_GamePlace1.y());
      assertEquals(1702, subject_GamePlace1.x());
      assertEquals("(1702, 2686)", subject_GamePlace1.toString());
      
      subject_GamePlace1.y(25);
      assertFalse(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertFalse(subject_GamePlace1.equals((Object)subject_GamePlace0));
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals(1702, subject_GamePlace0.x());
      assertEquals(2686, subject_GamePlace0.y());
      assertEquals("(1702, 2686)", subject_GamePlace0.toString());
      assertEquals(1702, subject_GamePlace1.x());
      assertEquals("(1702, 25)", subject_GamePlace1.toString());
      assertEquals(25, subject_GamePlace1.y());
      
      int int0 = subject_GamePlace0.manhattanDistance(subject_GamePlace1);
      assertFalse(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertFalse(subject_GamePlace1.equals((Object)subject_GamePlace0));
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals(1702, subject_GamePlace0.x());
      assertEquals(2686, subject_GamePlace0.y());
      assertEquals("(1702, 2686)", subject_GamePlace0.toString());
      assertEquals(1702, subject_GamePlace1.x());
      assertEquals("(1702, 25)", subject_GamePlace1.toString());
      assertEquals(25, subject_GamePlace1.y());
      assertEquals(2661, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, (-1));
      assertNotNull(subject_GamePlace0);
      assertEquals("(0, -1)", subject_GamePlace0.toString());
      assertEquals(0, subject_GamePlace0.x());
      assertEquals((-1), subject_GamePlace0.y());
      
      subject_GamePlace0.y(0);
      assertEquals("(0, 0)", subject_GamePlace0.toString());
      assertEquals(0, subject_GamePlace0.x());
      assertEquals(0, subject_GamePlace0.y());
      
      int int0 = subject_GamePlace0.manhattanDistance(subject_GamePlace0);
      assertEquals("(0, 0)", subject_GamePlace0.toString());
      assertEquals(0, subject_GamePlace0.x());
      assertEquals(0, subject_GamePlace0.y());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-185), (-3531));
      assertNotNull(subject_GamePlace0);
      assertEquals("(-185, -3531)", subject_GamePlace0.toString());
      assertEquals((-185), subject_GamePlace0.x());
      assertEquals((-3531), subject_GamePlace0.y());
      
      subject_GamePlace0.x(612);
      assertEquals("(612, -3531)", subject_GamePlace0.toString());
      assertEquals(612, subject_GamePlace0.x());
      assertEquals((-3531), subject_GamePlace0.y());
      
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      assertTrue(subject_GamePlace1.equals((Object)subject_GamePlace0));
      assertNotNull(subject_GamePlace1);
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals("(612, -3531)", subject_GamePlace0.toString());
      assertEquals(612, subject_GamePlace0.x());
      assertEquals((-3531), subject_GamePlace0.y());
      assertEquals(612, subject_GamePlace1.x());
      assertEquals((-3531), subject_GamePlace1.y());
      assertEquals("(612, -3531)", subject_GamePlace1.toString());
      
      subject_GamePlace1.x((-185));
      assertFalse(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertFalse(subject_GamePlace1.equals((Object)subject_GamePlace0));
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals("(612, -3531)", subject_GamePlace0.toString());
      assertEquals(612, subject_GamePlace0.x());
      assertEquals((-3531), subject_GamePlace0.y());
      assertEquals((-3531), subject_GamePlace1.y());
      assertEquals((-185), subject_GamePlace1.x());
      assertEquals("(-185, -3531)", subject_GamePlace1.toString());
      
      boolean boolean0 = subject_GamePlace1.equals(subject_GamePlace0);
      assertFalse(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertFalse(subject_GamePlace1.equals((Object)subject_GamePlace0));
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals("(612, -3531)", subject_GamePlace0.toString());
      assertEquals(612, subject_GamePlace0.x());
      assertEquals((-3531), subject_GamePlace0.y());
      assertEquals((-3531), subject_GamePlace1.y());
      assertEquals((-185), subject_GamePlace1.x());
      assertEquals("(-185, -3531)", subject_GamePlace1.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1975, (-745));
      assertNotNull(subject_GamePlace0);
      assertEquals(1975, subject_GamePlace0.x());
      assertEquals((-745), subject_GamePlace0.y());
      assertEquals("(1975, -745)", subject_GamePlace0.toString());
      
      int int0 = subject_GamePlace0.manhattanDistance((Subject.GamePlace) null);
      assertEquals(1975, subject_GamePlace0.x());
      assertEquals((-745), subject_GamePlace0.y());
      assertEquals("(1975, -745)", subject_GamePlace0.toString());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, (-1));
      assertNotNull(subject_GamePlace0);
      assertEquals("(0, -1)", subject_GamePlace0.toString());
      assertEquals(0, subject_GamePlace0.x());
      assertEquals((-1), subject_GamePlace0.y());
      
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      assertTrue(subject_GamePlace1.equals((Object)subject_GamePlace0));
      assertNotNull(subject_GamePlace1);
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals("(0, -1)", subject_GamePlace0.toString());
      assertEquals(0, subject_GamePlace0.x());
      assertEquals((-1), subject_GamePlace0.y());
      assertEquals(0, subject_GamePlace1.x());
      assertEquals((-1), subject_GamePlace1.y());
      assertEquals("(0, -1)", subject_GamePlace1.toString());
      
      subject_GamePlace0.y(0);
      assertFalse(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertEquals(0, subject_GamePlace0.y());
      assertEquals(0, subject_GamePlace0.x());
      assertEquals("(0, 0)", subject_GamePlace0.toString());
      
      boolean boolean0 = subject_GamePlace1.isAdjacent(subject_GamePlace0);
      assertFalse(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertFalse(subject_GamePlace1.equals((Object)subject_GamePlace0));
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals(0, subject_GamePlace0.y());
      assertEquals(0, subject_GamePlace0.x());
      assertEquals("(0, 0)", subject_GamePlace0.toString());
      assertEquals(0, subject_GamePlace1.x());
      assertEquals((-1), subject_GamePlace1.y());
      assertEquals("(0, -1)", subject_GamePlace1.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-409), (-409));
      assertNotNull(subject_GamePlace0);
      assertEquals((-409), subject_GamePlace0.x());
      assertEquals((-409), subject_GamePlace0.y());
      assertEquals("(-409, -409)", subject_GamePlace0.toString());
      
      boolean boolean0 = subject_GamePlace0.isAdjacent((Subject.GamePlace) null);
      assertEquals((-409), subject_GamePlace0.x());
      assertEquals((-409), subject_GamePlace0.y());
      assertEquals("(-409, -409)", subject_GamePlace0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(692, 1);
      assertNotNull(subject_GamePlace0);
      assertEquals(1, subject_GamePlace0.y());
      assertEquals(692, subject_GamePlace0.x());
      assertEquals("(692, 1)", subject_GamePlace0.toString());
      
      boolean boolean0 = subject_GamePlace0.isAdjacent(subject_GamePlace0);
      assertEquals(1, subject_GamePlace0.y());
      assertEquals(692, subject_GamePlace0.x());
      assertEquals("(692, 1)", subject_GamePlace0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(692, 1);
      assertNotNull(subject_GamePlace0);
      assertEquals("(692, 1)", subject_GamePlace0.toString());
      assertEquals(692, subject_GamePlace0.x());
      assertEquals(1, subject_GamePlace0.y());
      
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      assertTrue(subject_GamePlace1.equals((Object)subject_GamePlace0));
      assertNotNull(subject_GamePlace1);
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals("(692, 1)", subject_GamePlace0.toString());
      assertEquals(692, subject_GamePlace0.x());
      assertEquals(1, subject_GamePlace0.y());
      assertEquals(692, subject_GamePlace1.x());
      assertEquals(1, subject_GamePlace1.y());
      assertEquals("(692, 1)", subject_GamePlace1.toString());
      
      subject_GamePlace0.y(0);
      assertFalse(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertEquals(692, subject_GamePlace0.x());
      assertEquals("(692, 0)", subject_GamePlace0.toString());
      assertEquals(0, subject_GamePlace0.y());
      
      boolean boolean0 = subject_GamePlace1.equals(subject_GamePlace0);
      assertFalse(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertFalse(subject_GamePlace1.equals((Object)subject_GamePlace0));
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals(692, subject_GamePlace0.x());
      assertEquals("(692, 0)", subject_GamePlace0.toString());
      assertEquals(0, subject_GamePlace0.y());
      assertEquals(692, subject_GamePlace1.x());
      assertEquals(1, subject_GamePlace1.y());
      assertEquals("(692, 1)", subject_GamePlace1.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(10, 10);
      assertNotNull(subject_GamePlace0);
      assertEquals("(10, 10)", subject_GamePlace0.toString());
      assertEquals(10, subject_GamePlace0.x());
      assertEquals(10, subject_GamePlace0.y());
      
      Subject.GamePlace subject_GamePlace1 = subject0.new GamePlace((-1103), (-1103));
      assertFalse(subject_GamePlace1.equals((Object)subject_GamePlace0));
      assertNotNull(subject_GamePlace1);
      assertEquals("(-1103, -1103)", subject_GamePlace1.toString());
      assertEquals((-1103), subject_GamePlace1.y());
      assertEquals((-1103), subject_GamePlace1.x());
      
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace1);
      assertFalse(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertFalse(subject_GamePlace1.equals((Object)subject_GamePlace0));
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals("(10, 10)", subject_GamePlace0.toString());
      assertEquals(10, subject_GamePlace0.x());
      assertEquals(10, subject_GamePlace0.y());
      assertEquals("(-1103, -1103)", subject_GamePlace1.toString());
      assertEquals((-1103), subject_GamePlace1.y());
      assertEquals((-1103), subject_GamePlace1.x());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 0);
      assertNotNull(subject_GamePlace0);
      assertEquals("(0, 0)", subject_GamePlace0.toString());
      assertEquals(0, subject_GamePlace0.y());
      assertEquals(0, subject_GamePlace0.x());
      
      boolean boolean0 = subject_GamePlace0.equals((Object) null);
      assertEquals("(0, 0)", subject_GamePlace0.toString());
      assertEquals(0, subject_GamePlace0.y());
      assertEquals(0, subject_GamePlace0.x());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(10, 10);
      assertNotNull(subject_GamePlace0);
      assertEquals(10, subject_GamePlace0.y());
      assertEquals(10, subject_GamePlace0.x());
      assertEquals("(10, 10)", subject_GamePlace0.toString());
      
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace0);
      assertEquals(10, subject_GamePlace0.y());
      assertEquals(10, subject_GamePlace0.x());
      assertEquals("(10, 10)", subject_GamePlace0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(692, 1);
      assertNotNull(subject_GamePlace0);
      assertEquals(1, subject_GamePlace0.y());
      assertEquals(692, subject_GamePlace0.x());
      assertEquals("(692, 1)", subject_GamePlace0.toString());
      
      boolean boolean0 = subject_GamePlace0.equals("(692, -3824)");
      assertEquals(1, subject_GamePlace0.y());
      assertEquals(692, subject_GamePlace0.x());
      assertEquals("(692, 1)", subject_GamePlace0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(692, 1);
      assertNotNull(subject_GamePlace0);
      assertEquals("(692, 1)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.y());
      assertEquals(692, subject_GamePlace0.x());
      
      subject_GamePlace0.hashCode();
      assertEquals("(692, 1)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.y());
      assertEquals(692, subject_GamePlace0.x());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(692, 1);
      assertNotNull(subject_GamePlace0);
      assertEquals(692, subject_GamePlace0.x());
      assertEquals(1, subject_GamePlace0.y());
      assertEquals("(692, 1)", subject_GamePlace0.toString());
      
      subject_GamePlace0.y((-3824));
      assertEquals((-3824), subject_GamePlace0.y());
      assertEquals("(692, -3824)", subject_GamePlace0.toString());
      assertEquals(692, subject_GamePlace0.x());
      
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      assertTrue(subject_GamePlace1.equals((Object)subject_GamePlace0));
      assertNotNull(subject_GamePlace1);
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals((-3824), subject_GamePlace0.y());
      assertEquals("(692, -3824)", subject_GamePlace0.toString());
      assertEquals(692, subject_GamePlace0.x());
      assertEquals((-3824), subject_GamePlace1.y());
      assertEquals("(692, -3824)", subject_GamePlace1.toString());
      assertEquals(692, subject_GamePlace1.x());
      
      subject_GamePlace0.x(0);
      assertFalse(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertEquals((-3824), subject_GamePlace0.y());
      assertEquals("(0, -3824)", subject_GamePlace0.toString());
      assertEquals(0, subject_GamePlace0.x());
      
      subject_GamePlace1.y(0);
      assertFalse(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertFalse(subject_GamePlace1.equals((Object)subject_GamePlace0));
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals((-3824), subject_GamePlace0.y());
      assertEquals("(0, -3824)", subject_GamePlace0.toString());
      assertEquals(0, subject_GamePlace0.x());
      assertEquals(0, subject_GamePlace1.y());
      assertEquals("(692, 0)", subject_GamePlace1.toString());
      assertEquals(692, subject_GamePlace1.x());
      
      subject_GamePlace1.x(0);
      assertFalse(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertFalse(subject_GamePlace1.equals((Object)subject_GamePlace0));
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals((-3824), subject_GamePlace0.y());
      assertEquals("(0, -3824)", subject_GamePlace0.toString());
      assertEquals(0, subject_GamePlace0.x());
      assertEquals(0, subject_GamePlace1.y());
      assertEquals(0, subject_GamePlace1.x());
      assertEquals("(0, 0)", subject_GamePlace1.toString());
      
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace1);
      assertFalse(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertFalse(subject_GamePlace1.equals((Object)subject_GamePlace0));
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals((-3824), subject_GamePlace0.y());
      assertEquals("(0, -3824)", subject_GamePlace0.toString());
      assertEquals(0, subject_GamePlace0.x());
      assertEquals(0, subject_GamePlace1.y());
      assertEquals(0, subject_GamePlace1.x());
      assertEquals("(0, 0)", subject_GamePlace1.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(692, 1);
      assertNotNull(subject_GamePlace0);
      assertEquals("(692, 1)", subject_GamePlace0.toString());
      assertEquals(692, subject_GamePlace0.x());
      assertEquals(1, subject_GamePlace0.y());
      
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      assertTrue(subject_GamePlace1.equals((Object)subject_GamePlace0));
      assertNotNull(subject_GamePlace1);
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals("(692, 1)", subject_GamePlace0.toString());
      assertEquals(692, subject_GamePlace0.x());
      assertEquals(1, subject_GamePlace0.y());
      assertEquals(692, subject_GamePlace1.x());
      assertEquals(1, subject_GamePlace1.y());
      assertEquals("(692, 1)", subject_GamePlace1.toString());
      
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace1);
      assertTrue(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertTrue(subject_GamePlace1.equals((Object)subject_GamePlace0));
      assertNotSame(subject_GamePlace0, subject_GamePlace1);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals("(692, 1)", subject_GamePlace0.toString());
      assertEquals(692, subject_GamePlace0.x());
      assertEquals(1, subject_GamePlace0.y());
      assertEquals(692, subject_GamePlace1.x());
      assertEquals(1, subject_GamePlace1.y());
      assertEquals("(692, 1)", subject_GamePlace1.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(692, 1);
      assertNotNull(subject_GamePlace0);
      assertEquals("(692, 1)", subject_GamePlace0.toString());
      assertEquals(692, subject_GamePlace0.x());
      assertEquals(1, subject_GamePlace0.y());
      
      int int0 = subject_GamePlace0.x();
      assertEquals("(692, 1)", subject_GamePlace0.toString());
      assertEquals(692, subject_GamePlace0.x());
      assertEquals(1, subject_GamePlace0.y());
      assertEquals(692, int0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(692, 1);
      assertNotNull(subject_GamePlace0);
      assertEquals(1, subject_GamePlace0.y());
      assertEquals(692, subject_GamePlace0.x());
      assertEquals("(692, 1)", subject_GamePlace0.toString());
      
      int int0 = subject_GamePlace0.y();
      assertEquals(1, subject_GamePlace0.y());
      assertEquals(692, subject_GamePlace0.x());
      assertEquals("(692, 1)", subject_GamePlace0.toString());
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(692, 1);
      assertNotNull(subject_GamePlace0);
      assertEquals(692, subject_GamePlace0.x());
      assertEquals(1, subject_GamePlace0.y());
      assertEquals("(692, 1)", subject_GamePlace0.toString());
      
      String string0 = subject_GamePlace0.toString();
      assertNotNull(string0);
      assertEquals(692, subject_GamePlace0.x());
      assertEquals(1, subject_GamePlace0.y());
      assertEquals("(692, 1)", subject_GamePlace0.toString());
      assertEquals("(692, 1)", string0);
  }
}
