/*
 * This file was automatically generated by EvoSuite
 * Thu May 07 11:20:10 GMT 2026
 */

package comp5111.assignment.cut;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import comp5111.assignment.cut.Subject;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Subject$DateTimeAlgorithms_ESTest extends Subject$DateTimeAlgorithms_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween((-526), 1, (-618), 12);
      assertEquals((-1093), int0);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween((-1), 12, 11, 9);
      assertEquals(141, int0);
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth((-1704), 12);
      assertEquals("-1704-12-01", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("%04d-%02d-01", "-1819-07-01");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("-1819-07-01", "|[f,xr{(");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("9th");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Invalid date");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(8);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(6);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(3);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(12);
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(31);
      assertEquals("31st", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(0);
      assertEquals("(invalid)", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(13);
      assertEquals("13th", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(60L);
      assertEquals("1 M", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(3600L);
      assertEquals("1 H", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(86412L);
      assertEquals("1 D", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(4289895);
      assertEquals("7 W", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(2, 2, 28, 28, 28, 2);
      assertTrue(list0.isEmpty());
      assertEquals(0, list0.size());
      assertNotNull(list0);
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(25, 1, 25, 25, 1, (-526));
      assertEquals(0, list0.size());
      assertTrue(list0.isEmpty());
      assertNotNull(list0);
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      System.setCurrentTimeMillis(0L);
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDates((-1734), 2, 8, 14, 8, 8);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("0008-08-01", "0008-08-01");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      // Undeclared exception!
      Subject.DateTimeAlgorithms.listDatesBetween(5, 5, 5, 5, 5, 5);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(10);
      assertEquals("Oct", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(5);
      assertEquals("May", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(12);
      assertEquals("Dec", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(6);
      assertEquals("Jun", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(11);
      assertEquals("11th", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      boolean boolean0 = Subject.DateTimeAlgorithms.judgeLeapYear(0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      boolean boolean0 = Subject.DateTimeAlgorithms.judgeLeapYear(28);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      boolean boolean0 = Subject.DateTimeAlgorithms.judgeLeapYear(1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.calcDaysInMonth(12, 12);
      assertEquals(31, int0);
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.calcDaysInMonth(3, 9);
      assertEquals(30, int0);
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.calcDaysInMonth(4, 4);
      assertEquals(30, int0);
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.calcDaysInMonth(1370, 6);
      assertEquals(30, int0);
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.calcDaysInMonth(28, 2);
      assertEquals(29, int0);
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.calcDaysInMonth(2, 2);
      assertEquals(28, int0);
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.calcDaysInMonth((-1186), (-817));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.calcDaysInMonth(2620, 2620);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(7, 7, 2483, 2483);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(6, 6, 0, 0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(28, 28, 28, 28);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(25, (-952), 25, 1);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth(1548, 1548);
      assertEquals("(invalid)", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth(11, 11);
      assertEquals("0011-11-01", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth((-1226), (-1226));
      assertEquals("(invalid)", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(11, 11, 28, 4, 0, (-512));
      assertEquals(0, list0.size());
      assertTrue(list0.isEmpty());
      assertNotNull(list0);
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(Integer.MIN_VALUE, 1994, (-2146887454), 2261, 1865, 1392);
      assertEquals(0, list0.size());
      assertTrue(list0.isEmpty());
      assertNotNull(list0);
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("yyyy-MM-dd", "yyyy-MM-dd");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("%04d-%02d-%02d", "(invalid)");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("", "9Hb%arvy");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysInYear(2100);
      assertEquals(365, int0);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr((-512));
      assertEquals("(invalid)", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(11);
      assertEquals("Nov", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(1068, 10, 9);
      assertEquals("9th Oct 1068", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(9);
      assertEquals("Sep", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(8);
      assertEquals("Aug", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(7);
      assertEquals("Jul", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(4);
      assertEquals("Apr", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(3);
      assertEquals("Mar", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(2);
      assertEquals("Feb", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(1);
      assertEquals("Jan", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("f/H");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Dec");
      assertEquals(12, int0);
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Oct");
      assertEquals(10, int0);
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Aug");
      assertEquals(8, int0);
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jul");
      assertEquals(7, int0);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jun");
      assertEquals(6, int0);
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Nov");
      assertEquals(11, int0);
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Apr");
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Mar");
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Feb");
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jan");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("May");
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month((String) null);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(9);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(4);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(2);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(1640);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(Integer.MIN_VALUE);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr((-3393));
      assertEquals("(invalid)", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(3343);
      assertEquals("(invalid)", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(1592);
      assertEquals("(invalid)", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(12, 12, 12);
      assertEquals("12th Dec 12", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(1291L);
      assertEquals("22 M", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(3850L);
      assertEquals("1 H", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(86400L);
      assertEquals("1 D", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(604800L);
      assertEquals("1 W", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(86400000L);
      assertEquals("3 Y", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(0L);
      assertEquals("0 S", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysInYear(0);
      assertEquals(366, int0);
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      boolean boolean0 = Subject.DateTimeAlgorithms.judgeLeapYear((-700));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(6, 6, 4289895);
      assertEquals("(invalid)", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(0, 6, 0);
      assertEquals("(invalid)", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.calcDaysInMonth(11, 11);
      assertEquals(30, int0);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth(9, 9);
      assertEquals("0009-09-30", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(Integer.MIN_VALUE, 2, 2, 1, 1, 3);
      assertFalse(list0.isEmpty());
      assertEquals(1, list0.size());
      assertNotNull(list0);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth(5465456, 5465456);
      assertEquals("(invalid)", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.DateTimeAlgorithms.daysBetweenDates(6, 6, 6, 0, 0, 6);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid date
         //
         verifyException("comp5111.assignment.cut.Subject$DateTimeAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.DateTimeAlgorithms.daysBetweenDates(29, 2620, 10, (-122), (-122), 2);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid date
         //
         verifyException("comp5111.assignment.cut.Subject$DateTimeAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      Subject.DateTimeAlgorithms subject_DateTimeAlgorithms0 = new Subject.DateTimeAlgorithms();
      assertNotNull(subject_DateTimeAlgorithms0);
  }
}
