/*
 * This file was automatically generated by EvoSuite
 * Thu May 07 11:20:01 GMT 2026
 */

package comp5111.assignment.cut;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import comp5111.assignment.cut.Subject;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Subject$GamePlayer_ESTest extends Subject$GamePlayer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertNotNull(subject_GamePlayer0);
      
      subject_GamePlayer0.addScore((-1351));
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Anonymous Player', score=-1351}", subject_GamePlayer0.toString());
      assertEquals((-1351), subject_GamePlayer0.getScore());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertNotNull(subject_GamePlayer0);
      
      boolean boolean0 = subject_GamePlayer0.equals((Object) null);
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertNotNull(subject_GamePlayer0);
      
      boolean boolean0 = subject_GamePlayer0.equals(subject_GamePlayer0);
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertNotNull(subject_GamePlayer0);
      
      Object object0 = new Object();
      assertNotNull(object0);
      
      boolean boolean0 = subject_GamePlayer0.equals(object0);
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertNotNull(subject_GamePlayer0);
      
      subject_GamePlayer0.resetScore();
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertNotNull(subject_GamePlayer0);
      
      String string0 = subject_GamePlayer0.getName();
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals("Anonymous Player", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertNotNull(subject_GamePlayer0);
      
      Subject.GamePlayer subject_GamePlayer1 = subject_GamePlayer0.clone();
      assertTrue(subject_GamePlayer1.equals((Object)subject_GamePlayer0));
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer1.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer1.getName());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer1.toString());
      assertNotSame(subject_GamePlayer0, subject_GamePlayer1);
      assertNotSame(subject_GamePlayer1, subject_GamePlayer0);
      assertNotNull(subject_GamePlayer1);
      
      boolean boolean0 = subject_GamePlayer0.equals(subject_GamePlayer1);
      assertTrue(subject_GamePlayer0.equals((Object)subject_GamePlayer1));
      assertTrue(subject_GamePlayer1.equals((Object)subject_GamePlayer0));
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer1.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer1.getName());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer1.toString());
      assertNotSame(subject_GamePlayer0, subject_GamePlayer1);
      assertNotSame(subject_GamePlayer1, subject_GamePlayer0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertNotNull(subject_GamePlayer0);
      
      subject_GamePlayer0.setScore((-1351));
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Anonymous Player', score=-1351}", subject_GamePlayer0.toString());
      assertEquals((-1351), subject_GamePlayer0.getScore());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertNotNull(subject_GamePlayer0);
      
      int int0 = subject_GamePlayer0.getScore();
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertNotNull(subject_GamePlayer0);
      
      String string0 = subject_GamePlayer0.toString();
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer((String) null);
      assertNull(subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='null', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertNotNull(subject_GamePlayer0);
      
      Subject.GamePlayer subject_GamePlayer1 = subject0.new GamePlayer((String) null);
      assertEquals(0, subject_GamePlayer1.getScore());
      assertEquals("GamePlayer{name='null', score=0}", subject_GamePlayer1.toString());
      assertNull(subject_GamePlayer1.getName());
      assertNotNull(subject_GamePlayer1);
      
      // Undeclared exception!
      try { 
        subject_GamePlayer0.equals(subject_GamePlayer1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }
}
