/*
 * This file was automatically generated by EvoSuite
 * Thu May 07 11:20:11 GMT 2026
 */

package comp5111.assignment.cut;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import comp5111.assignment.cut.Subject;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Subject$GameConfiguration_ESTest extends Subject$GameConfiguration_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, 13);
      assertNotNull(subject_GamePlace0);
      assertEquals(13, subject_GamePlace0.y());
      assertEquals("(2, 13)", subject_GamePlace0.toString());
      assertEquals(2, subject_GamePlace0.x());
      
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertTrue(boolean0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(13, subject_GamePlace0.y());
      assertEquals("(2, 13)", subject_GamePlace0.toString());
      assertEquals(2, subject_GamePlace0.x());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(438, 3);
      assertNotNull(subject_GamePlace0);
      assertEquals("(438, 3)", subject_GamePlace0.toString());
      assertEquals(438, subject_GamePlace0.x());
      assertEquals(3, subject_GamePlace0.y());
      
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertTrue(boolean0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals("(438, 3)", subject_GamePlace0.toString());
      assertEquals(438, subject_GamePlace0.x());
      assertEquals(3, subject_GamePlace0.y());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(13, subject_GameConfiguration0.getSize());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 0);
      assertNotNull(subject_GamePlace0);
      assertEquals("(0, 0)", subject_GamePlace0.toString());
      assertEquals(0, subject_GamePlace0.x());
      assertEquals(0, subject_GamePlace0.y());
      
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertFalse(boolean0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertEquals("(0, 0)", subject_GamePlace0.toString());
      assertEquals(0, subject_GamePlace0.x());
      assertEquals(0, subject_GamePlace0.y());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 4425);
      assertNotNull(subject_GamePlace0);
      assertEquals(4425, subject_GamePlace0.y());
      assertEquals("(0, 4425)", subject_GamePlace0.toString());
      assertEquals(0, subject_GamePlace0.x());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(3, subject_GameConfiguration0.getSize());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 0);
      assertNotNull(subject_GamePlace0);
      assertEquals(0, subject_GamePlace0.x());
      assertEquals("(0, 0)", subject_GamePlace0.toString());
      assertEquals(0, subject_GamePlace0.y());
      
      Subject.GamePlayer subject_GamePlayer0 = subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
      assertNull(subject_GamePlayer0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertEquals(0, subject_GamePlace0.x());
      assertEquals("(0, 0)", subject_GamePlace0.toString());
      assertEquals(0, subject_GamePlace0.y());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(21);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(21, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(21, 21);
      assertNotNull(subject_GamePlace0);
      assertEquals("(21, 21)", subject_GamePlace0.toString());
      assertEquals(21, subject_GamePlace0.y());
      assertEquals(21, subject_GamePlace0.x());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player A");
      assertNotNull(subject_GamePlayer0);
      assertEquals("Player A", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, 2);
      assertNotNull(subject_GamePlace0);
      assertEquals(2, subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals("(2, 2)", subject_GamePlace0.toString());
      
      subject_GamePlace0.y(0);
      assertEquals("(2, 0)", subject_GamePlace0.toString());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals(0, subject_GamePlace0.y());
      
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals("Player A", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("(2, 0)", subject_GamePlace0.toString());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals(0, subject_GamePlace0.y());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player B");
      assertNotNull(subject_GamePlayer0);
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals("Player B", subject_GamePlayer0.getName());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 2);
      assertNotNull(subject_GamePlace0);
      assertEquals("(0, 2)", subject_GamePlace0.toString());
      assertEquals(2, subject_GamePlace0.y());
      assertEquals(0, subject_GamePlace0.x());
      
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals("Player B", subject_GamePlayer0.getName());
      assertEquals("(0, 2)", subject_GamePlace0.toString());
      assertEquals(2, subject_GamePlace0.y());
      assertEquals(0, subject_GamePlace0.x());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player B");
      assertNotNull(subject_GamePlayer0);
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Player B", subject_GamePlayer0.getName());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-1031), 22);
      assertNotNull(subject_GamePlace0);
      assertEquals(22, subject_GamePlace0.y());
      assertEquals((-1031), subject_GamePlace0.x());
      assertEquals("(-1031, 22)", subject_GamePlace0.toString());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // the place(-1031, 22) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player B");
      assertNotNull(subject_GamePlayer0);
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals("Player B", subject_GamePlayer0.getName());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-1031), 22);
      assertNotNull(subject_GamePlace0);
      assertEquals((-1031), subject_GamePlace0.x());
      assertEquals(22, subject_GamePlace0.y());
      assertEquals("(-1031, 22)", subject_GamePlace0.toString());
      
      subject_GamePlace0.x(1804);
      assertEquals(1804, subject_GamePlace0.x());
      assertEquals("(1804, 22)", subject_GamePlace0.toString());
      assertEquals(22, subject_GamePlace0.y());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // the place(1804, 22) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[9];
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(23, subject_GamePlayerArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // there must be exactly two players
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.isOccupied((Subject.GamePlace) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt((Subject.GamePlace) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(13, 13);
      assertNotNull(subject_GamePlace0);
      assertEquals(13, subject_GamePlace0.x());
      assertEquals(13, subject_GamePlace0.y());
      assertEquals("(13, 13)", subject_GamePlace0.toString());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece((Subject.GamePlayer) null, subject_GamePlace0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(21, (Subject.GamePlayer[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(13, subject_GameConfiguration0.getSize());
      
      subject_GameConfiguration0.clearInitialBoard();
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(13, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(3, subject_GameConfiguration0.getSize());
      
      boolean boolean0 = subject_GameConfiguration0.isBoardFull();
      assertFalse(boolean0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(3, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player B");
      assertNotNull(subject_GamePlayer0);
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Player B", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 2);
      assertNotNull(subject_GamePlace0);
      assertEquals("(1, 2)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Player B", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals("(1, 2)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getPlacesOfPlayer((Subject.GamePlayer) null);
      assertNotNull(list0);
      assertFalse(list0.contains(subject_GamePlace0));
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(list0.isEmpty());
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player B");
      assertNotNull(subject_GamePlayer0);
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals("Player B", subject_GamePlayer0.getName());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 2);
      assertNotNull(subject_GamePlace0);
      assertEquals("(1, 2)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals("Player B", subject_GamePlayer0.getName());
      assertEquals("(1, 2)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getPlacesOfPlayer(subject_GamePlayer0);
      assertNotNull(list0);
      assertTrue(list0.contains(subject_GamePlace0));
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals("Player B", subject_GamePlayer0.getName());
      assertEquals(1, list0.size());
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player B");
      assertNotNull(subject_GamePlayer0);
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Player B", subject_GamePlayer0.getName());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 2);
      assertNotNull(subject_GamePlace0);
      assertEquals(1, subject_GamePlace0.x());
      assertEquals("(1, 2)", subject_GamePlace0.toString());
      assertEquals(2, subject_GamePlace0.y());
      
      subject_GamePlace0.x(2);
      assertEquals(2, subject_GamePlace0.x());
      assertEquals("(2, 2)", subject_GamePlace0.toString());
      assertEquals(2, subject_GamePlace0.y());
      
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Player B", subject_GamePlayer0.getName());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals("(2, 2)", subject_GamePlace0.toString());
      assertEquals(2, subject_GamePlace0.y());
      
      boolean boolean0 = subject_GameConfiguration0.isBoardSymmetric();
      assertTrue(boolean0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player B");
      assertNotNull(subject_GamePlayer0);
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Player B", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 2);
      assertNotNull(subject_GamePlace0);
      assertEquals(2, subject_GamePlace0.y());
      assertEquals(1, subject_GamePlace0.x());
      assertEquals("(1, 2)", subject_GamePlace0.toString());
      
      subject_GamePlace0.x(3);
      assertEquals(3, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      assertEquals("(3, 2)", subject_GamePlace0.toString());
      
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Player B", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals(3, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      assertEquals("(3, 2)", subject_GamePlace0.toString());
      
      boolean boolean0 = subject_GameConfiguration0.isBoardSymmetric();
      assertFalse(boolean0);
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player B");
      assertNotNull(subject_GamePlayer0);
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals("Player B", subject_GamePlayer0.getName());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 2);
      assertNotNull(subject_GamePlace0);
      assertEquals("(1, 2)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals("Player B", subject_GamePlayer0.getName());
      assertEquals("(1, 2)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      
      boolean boolean0 = subject_GameConfiguration0.isBoardSymmetric();
      assertFalse(boolean0);
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player A");
      assertNotNull(subject_GamePlayer0);
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals("Player A", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, 2);
      assertNotNull(subject_GamePlace0);
      assertEquals(2, subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals("(2, 2)", subject_GamePlace0.toString());
      
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals("Player A", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals(2, subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals("(2, 2)", subject_GamePlace0.toString());
      
      int[] intArray0 = subject_GameConfiguration0.countPiecesPerPlayer();
      assertNotNull(intArray0);
      assertEquals(2, intArray0.length);
      assertArrayEquals(new int[] {1, 0}, intArray0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(13, subject_GameConfiguration0.getSize());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player B");
      assertNotNull(subject_GamePlayer0);
      assertEquals("Player B", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 2);
      assertNotNull(subject_GamePlace0);
      assertEquals("(1, 2)", subject_GamePlace0.toString());
      assertEquals(2, subject_GamePlace0.y());
      assertEquals(1, subject_GamePlace0.x());
      
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertEquals("Player B", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals("(1, 2)", subject_GamePlace0.toString());
      assertEquals(2, subject_GamePlace0.y());
      assertEquals(1, subject_GamePlace0.x());
      
      int[] intArray0 = subject_GameConfiguration0.countPiecesPerPlayer();
      assertNotNull(intArray0);
      assertEquals(2, intArray0.length);
      assertArrayEquals(new int[] {0, 1}, intArray0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player B");
      assertNotNull(subject_GamePlayer0);
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Player B", subject_GamePlayer0.getName());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 2);
      assertNotNull(subject_GamePlace0);
      assertEquals("(1, 2)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Player B", subject_GamePlayer0.getName());
      assertEquals("(1, 2)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertTrue(boolean0);
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertEquals("(1, 2)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(3, subject_GameConfiguration0.getSize());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, (-966));
      assertNotNull(subject_GamePlace0);
      assertEquals((-966), subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals("(2, -966)", subject_GamePlace0.toString());
      
      subject_GamePlace0.y(12);
      assertEquals(12, subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals("(2, 12)", subject_GamePlace0.toString());
      
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertTrue(boolean0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertEquals(12, subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals("(2, 12)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, (-966));
      assertNotNull(subject_GamePlace0);
      assertEquals((-966), subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals("(2, -966)", subject_GamePlace0.toString());
      
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertTrue(boolean0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals((-966), subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals("(2, -966)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 2);
      assertNotNull(subject_GamePlace0);
      assertEquals(2, subject_GamePlace0.y());
      assertEquals(1, subject_GamePlace0.x());
      assertEquals("(1, 2)", subject_GamePlace0.toString());
      
      subject_GamePlace0.x(13);
      assertEquals(13, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      assertEquals("(13, 2)", subject_GamePlace0.toString());
      
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertTrue(boolean0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(13, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      assertEquals("(13, 2)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(21);
      assertNotNull(subject_GameConfiguration0);
      assertEquals(21, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-40), 21);
      assertNotNull(subject_GamePlace0);
      assertEquals((-40), subject_GamePlace0.x());
      assertEquals(21, subject_GamePlace0.y());
      assertEquals("(-40, 21)", subject_GamePlace0.toString());
      
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertTrue(boolean0);
      assertEquals(21, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals((-40), subject_GamePlace0.x());
      assertEquals(21, subject_GamePlace0.y());
      assertEquals("(-40, 21)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player B");
      assertNotNull(subject_GamePlayer0);
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Player B", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 2);
      assertNotNull(subject_GamePlace0);
      assertEquals(2, subject_GamePlace0.y());
      assertEquals("(1, 2)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.x());
      
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Player B", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals(2, subject_GamePlace0.y());
      assertEquals("(1, 2)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.x());
      
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getEmptyPlaces();
      assertNotNull(list0);
      assertFalse(list0.contains(subject_GamePlace0));
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertFalse(list0.isEmpty());
      assertEquals(167, list0.size());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(13, subject_GameConfiguration0.getSize());
      
      String string0 = subject_GameConfiguration0.toString();
      assertNotNull(string0);
      assertEquals("GameConfiguration (size=13)\n. . . . . . . . . . . . .\n. . . . . . . . . . . . .\n. . . . . . . . . . . . .\n. . . . . . . . . . . . .\n. . . . . . . . . . . . .\n. . . . . . . . . . . . .\n. . . . . . . . . . . . .\n. . . . . . . . . . . . .\n. . . . . . . . . . . . .\n. . . . . . . . . . . . .\n. . . . . . . . . . . . .\n. . . . . . . . . . . . .\n. . . . . . . . . . . . .\n", string0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(13, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, 2);
      assertNotNull(subject_GamePlace0);
      assertEquals(2, subject_GamePlace0.y());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals("(2, 2)", subject_GamePlace0.toString());
      
      subject_GamePlace0.y(13);
      assertEquals(2, subject_GamePlace0.x());
      assertEquals(13, subject_GamePlace0.y());
      assertEquals("(2, 13)", subject_GamePlace0.toString());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(21);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(21, subject_GameConfiguration0.getSize());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, (-808));
      assertNotNull(subject_GamePlace0);
      assertEquals(0, subject_GamePlace0.x());
      assertEquals("(0, -808)", subject_GamePlace0.toString());
      assertEquals((-808), subject_GamePlace0.y());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(25, subject_GameConfiguration0.getSize());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(3897, 25);
      assertNotNull(subject_GamePlace0);
      assertEquals(3897, subject_GamePlace0.x());
      assertEquals("(3897, 25)", subject_GamePlace0.toString());
      assertEquals(25, subject_GamePlace0.y());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-1031), 22);
      assertNotNull(subject_GamePlace0);
      assertEquals("(-1031, 22)", subject_GamePlace0.toString());
      assertEquals(22, subject_GamePlace0.y());
      assertEquals((-1031), subject_GamePlace0.x());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlayer[][] subject_GamePlayerArray0 = subject_GameConfiguration0.getInitialBoard();
      assertNotNull(subject_GamePlayerArray0);
      assertEquals(3, subject_GamePlayerArray0.length);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GameConfiguration subject_GameConfiguration1 = subject_GameConfiguration0.clone();
      assertNotNull(subject_GameConfiguration1);
      assertNotSame(subject_GameConfiguration0, subject_GameConfiguration1);
      assertNotSame(subject_GameConfiguration1, subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration1.isBoardSymmetric());
      assertFalse(subject_GameConfiguration1.isBoardFull());
      assertEquals(13, subject_GameConfiguration1.getSize());
      assertFalse(subject_GameConfiguration1.equals((Object)subject_GameConfiguration0));
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player A");
      assertNotNull(subject_GamePlayer0);
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals("Player A", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, (-1276));
      assertNotNull(subject_GamePlace0);
      assertEquals("(2, -1276)", subject_GamePlace0.toString());
      assertEquals(2, subject_GamePlace0.x());
      assertEquals((-1276), subject_GamePlace0.y());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // the place(2, -1276) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player B");
      assertNotNull(subject_GamePlayer0);
      assertEquals("Player B", subject_GamePlayer0.getName());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-1031), 22);
      assertNotNull(subject_GamePlace0);
      assertEquals(22, subject_GamePlace0.y());
      assertEquals((-1031), subject_GamePlace0.x());
      assertEquals("(-1031, 22)", subject_GamePlace0.toString());
      
      subject_GamePlace0.y((-1));
      assertEquals((-1031), subject_GamePlace0.x());
      assertEquals("(-1031, -1)", subject_GamePlace0.toString());
      assertEquals((-1), subject_GamePlace0.y());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // the place(-1031, -1) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player B");
      assertNotNull(subject_GamePlayer0);
      assertEquals("Player B", subject_GamePlayer0.getName());
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 2);
      assertNotNull(subject_GamePlace0);
      assertEquals(1, subject_GamePlace0.x());
      assertEquals("(1, 2)", subject_GamePlace0.toString());
      assertEquals(2, subject_GamePlace0.y());
      
      subject_GamePlace0.x(13);
      assertEquals(13, subject_GamePlace0.x());
      assertEquals("(13, 2)", subject_GamePlace0.toString());
      assertEquals(2, subject_GamePlace0.y());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // the place(13, 2) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      assertNotNull(subject_GamePlayer0);
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, (-966));
      assertNotNull(subject_GamePlace0);
      assertEquals(2, subject_GamePlace0.x());
      assertEquals("(2, -966)", subject_GamePlace0.toString());
      assertEquals((-966), subject_GamePlace0.y());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // the player of the piece is unknown
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player B");
      assertNotNull(subject_GamePlayer0);
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Player B", subject_GamePlayer0.getName());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 2);
      assertNotNull(subject_GamePlace0);
      assertEquals("(1, 2)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
      assertEquals("GamePlayer{name='Player B', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Player B", subject_GamePlayer0.getName());
      assertEquals("(1, 2)", subject_GamePlace0.toString());
      assertEquals(1, subject_GamePlace0.x());
      assertEquals(2, subject_GamePlace0.y());
      
      String string0 = subject_GameConfiguration0.toString();
      assertNotNull(string0);
      assertEquals("GameConfiguration (size=13)\n. . . . . . . . . . . . .\n. . . . . . . . . . . . .\n. P . . . . . . . . . . .\n. . . . . . . . . . . . .\n. . . . . . . . . . . . .\n. . . . . . . . . . . . .\n. . . . . . . . . . . . .\n. . . . . . . . . . . . .\n. . . . . . . . . . . . .\n. . . . . . . . . . . . .\n. . . . . . . . . . . . .\n. . . . . . . . . . . . .\n. . . . . . . . . . . . .\n", string0);
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertFalse(subject_GameConfiguration0.isBoardSymmetric());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(3, subject_GameConfiguration0.getSize());
      
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Player A");
      assertNotNull(subject_GamePlayer0);
      assertEquals("GamePlayer{name='Player A', score=0}", subject_GamePlayer0.toString());
      assertEquals(0, subject_GamePlayer0.getScore());
      assertEquals("Player A", subject_GamePlayer0.getName());
      
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-4043), 3);
      assertNotNull(subject_GamePlace0);
      assertEquals((-4043), subject_GamePlace0.x());
      assertEquals("(-4043, 3)", subject_GamePlace0.toString());
      assertEquals(3, subject_GamePlace0.y());
      
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // the place(-4043, 3) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[0];
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(3, subject_GamePlayerArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // there must be exactly two players
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(4959);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard is at most 25
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(2256);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be an odd number
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[4];
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(2, subject_GamePlayerArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be at least 3
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertNotNull(subject_GameConfiguration0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      
      int int0 = subject_GameConfiguration0.getSize();
      assertEquals(3, int0);
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Subject subject0 = new Subject();
      assertNotNull(subject0);
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      assertNotNull(subject_GameConfiguration0);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(13, subject_GameConfiguration0.getSize());
      
      Subject.GamePlayer[] subject_GamePlayerArray0 = subject_GameConfiguration0.getPlayers();
      assertNotNull(subject_GamePlayerArray0);
      assertEquals(2, subject_GamePlayerArray0.length);
      assertTrue(subject_GameConfiguration0.isBoardSymmetric());
      assertFalse(subject_GameConfiguration0.isBoardFull());
      assertEquals(13, subject_GameConfiguration0.getSize());
  }
}
